import RHLean.Proof.SquareRootLowPrimeNoLibertyFiniteEquiv

open RHLean.Proof

/-!
Kernel-only smoke test for the processed-seat no-liberty Othello seam.

The carriers in this proof path are deliberately noncomputable, so this file
must not use `#eval`.
-/

#check squareRootLowPrimeProcessedSeatNoLibertyMate
#check squareRootLowPrimeProcessedSeatNoLibertyMate_mem
#check squareRootLowPrimeProcessedSeatNoLibertyMate_involutive
#check squareRootLowPrimeProcessedSeatNoLibertyMate_weight_neg
#check finiteOthelloStablePart_processedSeatNoLibertyMate_eq_descendingFrontier
#check squareRootLowPrimeProcessedSeatNoLibertyMate_stableMass_eq_runningImbalance
#check squareRootLowPrimeProcessedSeatNoLibertyBoundary
#check squareRootLowPrimeNoLibertyBoundaryWeight
#check SquareRootLowPrimeNoLibertyWeightEquiv
#check squareRootLowPrimeNoLibertyWeightEquiv_sum_eq
#check squareRootLowPrimeNoLibertyWeightEquiv_boundaryMass_eq_runningImbalance
