#!/usr/bin/env python3
"""Extract declarations relevant to the existing cofactor/root transport API.

This is a source-indexing aid only.  It records exact declaration names and
short surrounding excerpts so the quantitative frontier proof can import the
native map instead of creating a duplicate coordinate.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "RHLean"
OUTPUT = ROOT / "research" / "COFACTOR_ROOT_MAPPING_API.md"

DECL = re.compile(
    r"^(?:noncomputable\s+)?(?:private\s+)?"
    r"(def|abbrev|theorem|lemma|structure)\s+([A-Za-z0-9_'.]+)"
)
KEY = re.compile(
    r"cofactor|canonical.*root|root.*canonical|squareRoot.*(?:map|charge|owner|fibre|fiber|ancestry|successor|transport)|"
    r"(?:map|charge|owner|fibre|fiber|ancestry|successor|transport).*squareRoot",
    re.IGNORECASE,
)


def relevant(name: str, block: str, path: Path) -> bool:
    haystack = "\n".join((name, block, str(path)))
    return bool(KEY.search(haystack)) and (
        "canonicalCofactor" in block
        or "squareRoot" in haystack
        or "root" in haystack.lower()
    )


def main() -> None:
    rows: list[tuple[str, str, str, str]] = []
    for path in sorted(SOURCE_ROOT.rglob("*.lean")):
        lines = path.read_text(errors="replace").splitlines()
        for i, line in enumerate(lines):
            match = DECL.match(line.strip())
            if not match:
                continue
            kind, name = match.groups()
            start = max(0, i - 7)
            end = min(len(lines), i + 15)
            block = "\n".join(lines[start:end])
            if relevant(name, block, path):
                rel = path.relative_to(ROOT).as_posix()
                rows.append((rel, kind, name, block))

    lines = [
        "# Existing cofactor-to-root mapping API",
        "",
        "Generated by `research/extract_cofactor_root_api.py`.",
        "",
        "This index is deliberately broader than the final proof dependency. It",
        "collects declarations whose names or nearby source connect",
        "`canonicalCofactor` with square-root, ancestry, transport, owner, charge,",
        "or fibre coordinates.",
        "",
        f"**Declarations found:** {len(rows)}",
        "",
    ]
    for rel, kind, name, block in rows:
        lines += [
            f"## `{name}`",
            "",
            f"- Kind: `{kind}`",
            f"- Module: `{rel}`",
            "",
            "```lean",
            block,
            "```",
            "",
        ]
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT} with {len(rows)} declarations")


if __name__ == "__main__":
    main()
