import Mathlib
import «research.GLOBAL_RETURNED_CORE_THRESHOLD_WALL_PAIR_FILTRATION»

/-!
# Finite telescope for a single threshold wall

The one-coordinate wall filtration already proves the exact fresh-prime step

  E(S) = E(insert r S) + Cross(S,r).

This file iterates that identity over an arbitrary duplicate-free list of fresh
prime coordinates.  It then specializes to revealing every prime coordinate of
one finite wall.  The result is the exact finite statement wanted for the
q^2-resolved attack: the total signed crossing ledger equals initial wall
energy minus its fully-revealed diagonal.

No limit, norm, Cauchy--Schwarz estimate, or RH assumption is used.
-/

noncomputable section
open scoped BigOperators

namespace RHLean.Proof

open RHLean.Analysis RHLean.Arithmetic

attribute [local instance] Classical.propDecidable

/-- Crossing ledger generated by revealing a list of coordinates successively
from an initial revealed set. -/
def lowOwnerThresholdWallListCrossMass
    (p y : ℕ) : Finset ℕ → List ℕ → ℝ
  | _S, [] => 0
  | S, r :: rs =>
      lowOwnerThresholdWallRevealedCrossPairMass p y S r +
        lowOwnerThresholdWallListCrossMass p y (insert r S) rs

/-- Final revealed set after successively inserting a list of coordinates. -/
def lowOwnerRevealList : Finset ℕ → List ℕ → Finset ℕ
  | S, [] => S
  | S, r :: rs => lowOwnerRevealList (insert r S) rs

@[simp] theorem lowOwnerRevealList_eq_union_toFinset
    (S : Finset ℕ) (rs : List ℕ) :
    lowOwnerRevealList S rs = S ∪ rs.toFinset := by
  induction rs generalizing S with
  | nil => simp [lowOwnerRevealList]
  | cons r rs ih =>
      simp only [lowOwnerRevealList, ih, List.toFinset_cons]
      ext q
      simp [or_assoc, or_left_comm, or_comm]

/-- **Exact finite wall telescope.**

If every listed coordinate is prime, the list has no repetitions, and none of
its coordinates has already been revealed, the sum of its successive crossing
packets is exactly the wall-energy drop from the initial set to the final set. -/
theorem lowOwnerThresholdWallListCrossMass_eq_energyDrop
    {p y : ℕ} :
    ∀ (S : Finset ℕ) (rs : List ℕ),
      rs.Nodup →
      (∀ r ∈ rs, r.Prime) →
      (∀ r ∈ rs, r ∉ S) →
      lowOwnerThresholdWallListCrossMass p y S rs =
        lowOwnerThresholdWallRevealedPairEnergy p y S -
          lowOwnerThresholdWallRevealedPairEnergy p y
            (lowOwnerRevealList S rs) := by
  intro S rs hnod hprime hfresh
  induction rs generalizing S with
  | nil =>
      simp [lowOwnerThresholdWallListCrossMass, lowOwnerRevealList]
  | cons r rs ih =>
      have hrPrime : r.Prime := hprime r (by simp)
      have hrFreshS : r ∉ S := hfresh r (by simp)
      have hnodTail : rs.Nodup := (List.nodup_cons.mp hnod).2
      have hrNotTail : r ∉ rs := (List.nodup_cons.mp hnod).1
      have hprimeTail : ∀ q ∈ rs, q.Prime := by
        intro q hq
        exact hprime q (by simp [hq])
      have hfreshTail : ∀ q ∈ rs, q ∉ insert r S := by
        intro q hq
        have hqS : q ∉ S := hfresh q (by simp [hq])
        have hqr : q ≠ r := by
          intro heq
          subst q
          exact hrNotTail hq
        simp [hqr, hqS]
      have hstep :=
        lowOwnerThresholdWallRevealedPairEnergy_eq_insert_add_cross
          (R := 0) (S := S) hrPrime hrFreshS
      have htail := ih (insert r S) hnodTail hprimeTail hfreshTail
      simp only [lowOwnerThresholdWallListCrossMass, lowOwnerRevealList]
      linarith

/-- Revealing all primes up to the wall cutoff, from the empty state, gives an
exact diagonal-completed telescope. -/
theorem lowOwnerThresholdWall_allPrimeListCrossMass_eq_empty_sub_diagonal
    (p y : ℕ) :
    lowOwnerThresholdWallListCrossMass p y ∅ (primesUpTo y).toList =
      lowOwnerThresholdWallRevealedPairEnergy p y ∅ -
        (∑ n ∈ lowOwnerThresholdMertensCrossingCarrier p y,
          realMoebiusStep n ^ 2) := by
  have hnod : (primesUpTo y).toList.Nodup := Finset.nodup_toList _
  have hprime : ∀ r ∈ (primesUpTo y).toList, r.Prime := by
    intro r hr
    have hrMem : r ∈ primesUpTo y := by simpa using hr
    exact (mem_primesUpTo.mp hrMem).1
  have hfresh : ∀ r ∈ (primesUpTo y).toList, r ∉ (∅ : Finset ℕ) := by
    simp
  have htel :=
    lowOwnerThresholdWallListCrossMass_eq_energyDrop
      (p := p) (y := y) (S := ∅) (rs := (primesUpTo y).toList)
      hnod hprime hfresh
  rw [lowOwnerRevealList_eq_union_toFinset] at htel
  simp only [Finset.empty_union, Finset.coe_sort_coe] at htel
  have hfinal :
      lowOwnerRevealList (∅ : Finset ℕ) (primesUpTo y).toList =
        primesUpTo y := by
    rw [lowOwnerRevealList_eq_union_toFinset]
    simp
  rw [hfinal] at htel
  rw [lowOwnerThresholdWallRevealedPairEnergy_full_eq_diagonal] at htel
  exact htel

/-- **Finite q²-wall budget.**

The full signed owner-crossing telescope at one q² daughter cutoff is no larger
than the literal q² child energy, because the fully-revealed terminal is a
nonnegative squarefree diagonal. -/
theorem lowOwnerQ2ThresholdWall_allPrimeListCrossMass_le_childEnergy
    (R q p : ℕ) :
    lowOwnerThresholdWallListCrossMass p (rawQ2ChildCutoff R q)
        ∅ (primesUpTo (rawQ2ChildCutoff R q)).toList ≤
      rawQ2ChildEnergyReal R q := by
  rw [lowOwnerThresholdWall_allPrimeListCrossMass_eq_empty_sub_diagonal]
  have hempty :=
    lowOwnerQ2ThresholdWallRevealedPairEnergy_empty_eq_childEnergy
      (R := R) (q := q) (p := p)
  rw [hempty]
  have hdiag :
      0 ≤
        ∑ n ∈ lowOwnerThresholdMertensCrossingCarrier
            p (rawQ2ChildCutoff R q),
          realMoebiusStep n ^ 2 := by
    apply Finset.sum_nonneg
    intro n _hn
    positivity
  linarith

end RHLean.Proof
