import Mathlib
import «research.GLOBAL_RETURNED_CORE_STOKES_BOUNDARY_IDENTIFICATION»

/-!
# One-dimensional amplitude factorization of Stokes clip steps

The Stokes scalar entering one first-owner cell is not a generic pair weight.
It is a symmetric cross form

  Cross(L,J)(a,b) = -L(a)J(b) - J(a)L(b),

with L the Dirichlet base coefficient and J the returned-child coefficient.

Two facts are exact:

* a mixed prime difference preserves this cross form, replacing L,J by their
  one-dimensional prime differences;
* on a product carrier, every Stokes escape face therefore factors into
  products of one-dimensional signed amplitudes.

This is the legal bridge needed before any frame estimate.  It removes the pair
carrier without taking absolute values, squaring cells separately, or dropping
the mixed Dirichlet payload.
-/

noncomputable section
open scoped BigOperators

namespace RHLean.Proof

open RHLean.Analysis RHLean.Arithmetic

attribute [local instance] Classical.propDecidable

/-- Symmetric cross scalar generated by two one-dimensional coefficient fields. -/
def lowOwnerStokesCrossScalar
    (L J : ℕ → ℝ) (mn : ℕ × ℕ) : ℝ :=
  -(L mn.1 * J mn.2) - J mn.1 * L mn.2

/-- One-dimensional multiplicative toggle difference. -/
def lowOwnerStokesToggleDifference
    (r : ℕ) (f : ℕ → ℝ) (n : ℕ) : ℝ :=
  f n - f (primeCarrierToggle r n)

/-- The physical first-owner polarization scalar is exactly a cross scalar. -/
theorem lowOwnerFirstOwnerDirichletPolarizationScalar_eq_cross
    (R p : ℕ) :
    lowOwnerFirstOwnerDirichletPolarizationScalar R p =
      lowOwnerStokesCrossScalar
        (lowOwnerDirichletBaseCoefficient R)
        (lowOwnerDirichletReturnedCoefficient R p) := by
  funext mn
  rcases mn with ⟨a, b⟩
  unfold lowOwnerFirstOwnerDirichletPolarizationScalar
    lowOwnerStokesCrossScalar
    lowOwnerDirichletIncidenceCoefficient
  ring

/-- **Cross-form closure under a mixed prime difference.** -/
theorem pairPrimeMixedDifference_crossScalar
    (r : ℕ) (L J : ℕ → ℝ) :
    pairPrimeMixedDifference r (lowOwnerStokesCrossScalar L J) =
      lowOwnerStokesCrossScalar
        (lowOwnerStokesToggleDifference r L)
        (lowOwnerStokesToggleDifference r J) := by
  funext mn
  rcases mn with ⟨a, b⟩
  unfold pairPrimeMixedDifference
    pairPrimeCarrierToggleLeft pairPrimeCarrierToggleRight
    lowOwnerStokesCrossScalar lowOwnerStokesToggleDifference
  simp only
  ring

/-- Signed one-dimensional amplitude on an arbitrary finite carrier. -/
def lowOwnerStokesSignedAmplitude
    (S : Finset ℕ) (f : ℕ → ℝ) : ℝ :=
  ∑ n ∈ S, othelloRealMoebius n * f n

/-- A cross scalar on a Cartesian product factors into two signed amplitude
products, with all signs retained. -/
theorem pairWeightedStokesMass_product_crossScalar
    (A B : Finset ℕ) (L J : ℕ → ℝ) :
    pairWeightedStokesMass (A.product B) (lowOwnerStokesCrossScalar L J) =
      -(lowOwnerStokesSignedAmplitude A L *
          lowOwnerStokesSignedAmplitude B J) -
        lowOwnerStokesSignedAmplitude A J *
          lowOwnerStokesSignedAmplitude B L := by
  unfold pairWeightedStokesMass lowOwnerStokesCrossScalar
    lowOwnerStokesSignedAmplitude othelloRealMoebiusPair
  rw [Finset.sum_sub_distrib, Finset.sum_neg_distrib]
  have hLJ :
      (∑ mn ∈ A.product B,
        (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
          (L mn.1 * J mn.2)) =
        (∑ a ∈ A, othelloRealMoebius a * L a) *
          (∑ b ∈ B, othelloRealMoebius b * J b) := by
    calc
      (∑ mn ∈ A.product B,
        (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
          (L mn.1 * J mn.2)) =
        ∑ a ∈ A, ∑ b ∈ B,
          (othelloRealMoebius a * L a) *
            (othelloRealMoebius b * J b) := by
              simpa only [mul_assoc, mul_left_comm, mul_comm] using
                (Finset.sum_product
                  (s := A) (t := B)
                  (f := fun mn : ℕ × ℕ =>
                    (othelloRealMoebius mn.1 * L mn.1) *
                      (othelloRealMoebius mn.2 * J mn.2)))
      _ = ∑ a ∈ A,
          (othelloRealMoebius a * L a) *
            (∑ b ∈ B, othelloRealMoebius b * J b) := by
              apply Finset.sum_congr rfl
              intro a _ha
              rw [Finset.mul_sum]
      _ = _ := by rw [Finset.sum_mul]
  have hJL :
      (∑ mn ∈ A.product B,
        (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
          (J mn.1 * L mn.2)) =
        (∑ a ∈ A, othelloRealMoebius a * J a) *
          (∑ b ∈ B, othelloRealMoebius b * L b) := by
    calc
      (∑ mn ∈ A.product B,
        (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
          (J mn.1 * L mn.2)) =
        ∑ a ∈ A, ∑ b ∈ B,
          (othelloRealMoebius a * J a) *
            (othelloRealMoebius b * L b) := by
              simpa only [mul_assoc, mul_left_comm, mul_comm] using
                (Finset.sum_product
                  (s := A) (t := B)
                  (f := fun mn : ℕ × ℕ =>
                    (othelloRealMoebius mn.1 * J mn.1) *
                      (othelloRealMoebius mn.2 * L mn.2)))
      _ = ∑ a ∈ A,
          (othelloRealMoebius a * J a) *
            (∑ b ∈ B, othelloRealMoebius b * L b) := by
              apply Finset.sum_congr rfl
              intro a _ha
              rw [Finset.mul_sum]
      _ = _ := by rw [Finset.sum_mul]
  rw [hLJ, hJL]

/-- The left-toggle difference of a cross scalar is again a one-sided cross
form, with only the left coefficient fields differenced. -/
theorem crossScalar_sub_leftToggle
    (r : ℕ) (L J : ℕ → ℝ) (mn : ℕ × ℕ) :
    lowOwnerStokesCrossScalar L J mn -
        lowOwnerStokesCrossScalar L J (pairPrimeCarrierToggleLeft r mn) =
      -(lowOwnerStokesToggleDifference r L mn.1 * J mn.2) -
        lowOwnerStokesToggleDifference r J mn.1 * L mn.2 := by
  rcases mn with ⟨a, b⟩
  unfold lowOwnerStokesCrossScalar lowOwnerStokesToggleDifference
    pairPrimeCarrierToggleLeft
  simp only
  ring

/-- **One-dimensional factorization of one product-carrier Stokes boundary
step.**  The pair escape ledger contains only four products of signed
one-dimensional amplitudes. -/
theorem pairWeightedStokesBoundaryStep_product_crossScalar
    (r : ℕ) (A : Finset ℕ) (L J : ℕ → ℝ) :
    pairWeightedStokesBoundaryStep r (A.product A)
        (lowOwnerStokesCrossScalar L J) =
      -(lowOwnerStokesSignedAmplitude (primeEscapePart r A) L *
          lowOwnerStokesSignedAmplitude A J) -
        lowOwnerStokesSignedAmplitude (primeEscapePart r A) J *
          lowOwnerStokesSignedAmplitude A L +
      (1 / 2 : ℝ) *
        (-(lowOwnerStokesSignedAmplitude (primeInteriorPart r A)
              (lowOwnerStokesToggleDifference r L) *
            lowOwnerStokesSignedAmplitude (primeEscapePart r A) J) -
          lowOwnerStokesSignedAmplitude (primeInteriorPart r A)
              (lowOwnerStokesToggleDifference r J) *
            lowOwnerStokesSignedAmplitude (primeEscapePart r A) L) := by
  unfold pairWeightedStokesBoundaryStep
  rw [pairPrimeLeftEscapePart_product,
    pairPrimeRightEscapeAfterLeft_product]
  rw [pairWeightedStokesMass_product_crossScalar]
  have hright :
      (∑ mn ∈
        (primeInteriorPart r A).product (primeEscapePart r A),
        othelloRealMoebiusPair mn *
          (lowOwnerStokesCrossScalar L J mn -
            lowOwnerStokesCrossScalar L J
              (pairPrimeCarrierToggleLeft r mn))) =
        -(lowOwnerStokesSignedAmplitude (primeInteriorPart r A)
            (lowOwnerStokesToggleDifference r L) *
          lowOwnerStokesSignedAmplitude (primeEscapePart r A) J) -
        lowOwnerStokesSignedAmplitude (primeInteriorPart r A)
            (lowOwnerStokesToggleDifference r J) *
          lowOwnerStokesSignedAmplitude (primeEscapePart r A) L := by
    unfold lowOwnerStokesSignedAmplitude othelloRealMoebiusPair
    rw [Finset.sum_sub_distrib, Finset.sum_neg_distrib]
    have h1 :
        (∑ mn ∈ (primeInteriorPart r A).product (primeEscapePart r A),
          (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
            (lowOwnerStokesToggleDifference r L mn.1 * J mn.2)) =
          (∑ a ∈ primeInteriorPart r A,
              othelloRealMoebius a * lowOwnerStokesToggleDifference r L a) *
            (∑ b ∈ primeEscapePart r A,
              othelloRealMoebius b * J b) := by
      calc
        _ = ∑ a ∈ primeInteriorPart r A,
            ∑ b ∈ primeEscapePart r A,
              (othelloRealMoebius a * lowOwnerStokesToggleDifference r L a) *
                (othelloRealMoebius b * J b) := by
                  simpa only [mul_assoc, mul_left_comm, mul_comm] using
                    (Finset.sum_product
                      (s := primeInteriorPart r A)
                      (t := primeEscapePart r A)
                      (f := fun mn : ℕ × ℕ =>
                        (othelloRealMoebius mn.1 *
                          lowOwnerStokesToggleDifference r L mn.1) *
                        (othelloRealMoebius mn.2 * J mn.2)))
        _ = ∑ a ∈ primeInteriorPart r A,
            (othelloRealMoebius a * lowOwnerStokesToggleDifference r L a) *
              (∑ b ∈ primeEscapePart r A,
                othelloRealMoebius b * J b) := by
                  apply Finset.sum_congr rfl
                  intro a _ha
                  rw [Finset.mul_sum]
        _ = _ := by rw [Finset.sum_mul]
    have h2 :
        (∑ mn ∈ (primeInteriorPart r A).product (primeEscapePart r A),
          (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
            (lowOwnerStokesToggleDifference r J mn.1 * L mn.2)) =
          (∑ a ∈ primeInteriorPart r A,
              othelloRealMoebius a * lowOwnerStokesToggleDifference r J a) *
            (∑ b ∈ primeEscapePart r A,
              othelloRealMoebius b * L b) := by
      calc
        _ = ∑ a ∈ primeInteriorPart r A,
            ∑ b ∈ primeEscapePart r A,
              (othelloRealMoebius a * lowOwnerStokesToggleDifference r J a) *
                (othelloRealMoebius b * L b) := by
                  simpa only [mul_assoc, mul_left_comm, mul_comm] using
                    (Finset.sum_product
                      (s := primeInteriorPart r A)
                      (t := primeEscapePart r A)
                      (f := fun mn : ℕ × ℕ =>
                        (othelloRealMoebius mn.1 *
                          lowOwnerStokesToggleDifference r J mn.1) *
                        (othelloRealMoebius mn.2 * L mn.2)))
        _ = ∑ a ∈ primeInteriorPart r A,
            (othelloRealMoebius a * lowOwnerStokesToggleDifference r J a) *
              (∑ b ∈ primeEscapePart r A,
                othelloRealMoebius b * L b) := by
                  apply Finset.sum_congr rfl
                  intro a _ha
                  rw [Finset.mul_sum]
        _ = _ := by rw [Finset.sum_mul]
    calc
      (∑ mn ∈ (primeInteriorPart r A).product (primeEscapePart r A),
        othelloRealMoebiusPair mn *
          (lowOwnerStokesCrossScalar L J mn -
            lowOwnerStokesCrossScalar L J
              (pairPrimeCarrierToggleLeft r mn))) =
        ∑ mn ∈ (primeInteriorPart r A).product (primeEscapePart r A),
          othelloRealMoebiusPair mn *
            (-(lowOwnerStokesToggleDifference r L mn.1 * J mn.2) -
              lowOwnerStokesToggleDifference r J mn.1 * L mn.2) := by
                apply Finset.sum_congr rfl
                intro mn _hmn
                rw [crossScalar_sub_leftToggle]
      _ = _ := by
        unfold othelloRealMoebiusPair
        rw [Finset.sum_sub_distrib, Finset.sum_neg_distrib, h1, h2]
  rw [hright]

/-- Specialization to the literal first-owner Dirichlet polarization. -/
theorem lowOwnerFirstOwner_pairBoundaryStep_eq_signedAmplitudeProducts
    {R p r : ℕ} {sig : Finset ℕ} :
    pairWeightedStokesBoundaryStep r
        (lowOwnerFirstOwnerSignedCellPairCarrier R p sig)
        (lowOwnerFirstOwnerDirichletPolarizationScalar R p) =
      pairWeightedStokesBoundaryStep r
        ((lowOwnerFirstOwnerBaseFiber R p sig).product
          (lowOwnerFirstOwnerBaseFiber R p sig))
        (lowOwnerStokesCrossScalar
          (lowOwnerDirichletBaseCoefficient R)
          (lowOwnerDirichletReturnedCoefficient R p)) := by
  unfold lowOwnerFirstOwnerSignedCellPairCarrier
  rw [lowOwnerFirstOwnerDirichletPolarizationScalar_eq_cross]

end RHLean.Proof
