import Mathlib
import RHLean.Arithmetic.PrimeWheelMobiusRecovery
import «research.GLOBAL_RETURNED_CORE_STOKES_GLOBAL_IDENTIFICATION»

/-!
# Exact corrected-wheel identification of the signed Stokes ledger

This file is still before every harmonic estimate.

The globally identified Stokes boundary is a Möbius-weighted pair ledger on the
physical clock `1 <= n <= X_R`.  Put on that same finite clock the corrected
prime-wheel site field generated by every prime through `sqrt X_R`.  The general
finite-wheel recovery theorem proves pointwise that this corrected field is
*exactly* Möbius at every physical Stokes site.

Consequently the final Stokes boundary can be rewritten exactly as a pair Gram
whose two arithmetic signs are corrected-wheel site values and whose scalar is
still the repository's literal Dirichlet polarization.  No conductor packet,
Fourier mode, norm, or inequality is introduced here.

This theorem is deliberately weaker than a conductor-boundary identification:
it only licenses the next algebraic question.  One must still prove that this
corrected-site pair ledger decomposes into the corrected boundary packets in the
legal direction before any endpoint frame can be applied.
-/

noncomputable section
open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

open RHLean.Analysis RHLean.Arithmetic

attribute [local instance] Classical.propDecidable

/-- Prime coordinates sufficient to recover Möbius on the entire physical
Stokes clock. -/
def lowOwnerStokesWheelPrimes (R : ℕ) : Finset ℕ :=
  primesUpTo (Nat.sqrt (squareRootEndpoint R))

/-- Corrected finite-wheel site on the Stokes clock, cast to the real currency
used by the signed pair ledger. -/
def lowOwnerStokesCorrectedSite (R n : ℕ) : ℝ :=
  ((correctedPrimeWheelSite
      (lowOwnerStokesWheelPrimes R) (squareRootEndpoint R) n : ℤ) : ℝ)

/-- The chosen coordinate set consists only of genuine primes. -/
theorem lowOwnerStokesWheelPrimes_prime
    {R p : ℕ} (hp : p ∈ lowOwnerStokesWheelPrimes R) :
    p.Prime := by
  unfold lowOwnerStokesWheelPrimes at hp
  exact prime_of_mem_primesUpTo hp

/-- The chosen coordinates cover every prime through the square root of the
physical endpoint, exactly the hypothesis required by finite-wheel Möbius
recovery. -/
theorem lowOwnerStokesWheelPrimes_sqrtCoverage (R : ℕ) :
    PrimeWheelSqrtCoverage
      (lowOwnerStokesWheelPrimes R) (squareRootEndpoint R) := by
  intro p hp hple
  unfold lowOwnerStokesWheelPrimes
  exact mem_primesUpTo_of_prime_le hp hple

/-- **Pointwise corrected-wheel recovery on every actual Stokes site.** -/
theorem lowOwnerStokesCorrectedSite_eq_realMoebiusStep
    {R n : ℕ} (hn : n ∈ lowOwnerNonzeroMobiusCarrier R) :
    lowOwnerStokesCorrectedSite R n = realMoebiusStep n := by
  rcases lowOwnerNonzeroMobiusCarrier_squarefree_pos hn with ⟨_hsq, hnpos⟩
  have hnIcc := (Finset.mem_filter.mp hn).1
  have hnX : n ≤ squareRootEndpoint R := (Finset.mem_Icc.mp hnIcc).2
  have hrec := correctedPrimeWheelSite_eq_moebius
    (S := lowOwnerStokesWheelPrimes R)
    (upper := squareRootEndpoint R)
    (n := n)
    (fun p hp => lowOwnerStokesWheelPrimes_prime hp)
    (lowOwnerStokesWheelPrimes_sqrtCoverage R)
    hnpos hnX
  unfold lowOwnerStokesCorrectedSite RHLean.Analysis.realMoebiusStep
  rw [hrec]

/-- Product of the two exact corrected-wheel site values on one ordered pair. -/
def lowOwnerStokesCorrectedPairWeight
    (R : ℕ) (mn : ℕ × ℕ) : ℝ :=
  lowOwnerStokesCorrectedSite R mn.1 *
    lowOwnerStokesCorrectedSite R mn.2

/-- On every actual first-owner/signature pair carrier, the corrected-wheel pair
weight is literally the Möbius pair weight used by Othello/Stokes. -/
theorem lowOwnerStokesCorrectedPairWeight_eq_othelloPair
    {R p : ℕ} {sig : Finset ℕ} {mn : ℕ × ℕ}
    (hmn : mn ∈ lowOwnerFirstOwnerSignedCellPairCarrier R p sig) :
    lowOwnerStokesCorrectedPairWeight R mn =
      othelloRealMoebiusPair mn := by
  rcases Finset.mem_product.mp hmn with ⟨hm, hn⟩
  have hmCar : mn.1 ∈ lowOwnerNonzeroMobiusCarrier R :=
    (Finset.mem_filter.mp hm).1
  have hnCar : mn.2 ∈ lowOwnerNonzeroMobiusCarrier R :=
    (Finset.mem_filter.mp hn).1
  rw [lowOwnerStokesCorrectedPairWeight,
    lowOwnerStokesCorrectedSite_eq_realMoebiusStep hmCar,
    lowOwnerStokesCorrectedSite_eq_realMoebiusStep hnCar]
  unfold othelloRealMoebiusPair othelloRealMoebius
    RHLean.Analysis.realMoebiusStep
  ring

/-- Global corrected-site pair ledger carrying the *same* Dirichlet
polarization scalar as the physical Stokes boundary. -/
def lowOwnerCanonicalSignedStokesCorrectedWheelLedger
    (R : ℕ) : ℝ :=
  ∑ p ∈ primesUpTo (squareRootEndpoint R),
    ∑ sig ∈ lowOwnerFirstOwnerSignatureSet R p,
      ∑ mn ∈ lowOwnerFirstOwnerSignedCellPairCarrier R p sig,
        lowOwnerStokesCorrectedPairWeight R mn *
          lowOwnerFirstOwnerDirichletPolarizationScalar R p mn

/-- **Exact Stokes -> corrected-wheel site bridge.**

The final signed Stokes boundary is exactly the corrected-wheel pair ledger on
the same physical carrier.  This is an identity, not a frame estimate and not
yet a conductor-boundary decomposition. -/
theorem lowOwnerCanonicalSignedStokesFinalBoundary_eq_correctedWheelLedger
    {R : ℕ} (hR : 2 ≤ R) :
    lowOwnerCanonicalSignedStokesFinalBoundary R =
      lowOwnerCanonicalSignedStokesCorrectedWheelLedger R := by
  rw [lowOwnerCanonicalSignedStokesFinalBoundary_eq_dirichletPolarizationLedger hR]
  unfold lowOwnerCanonicalSignedStokesDirichletPolarizationLedger
    lowOwnerCanonicalSignedStokesCorrectedWheelLedger
  apply Finset.sum_congr rfl
  intro p _hp
  apply Finset.sum_congr rfl
  intro sig _hsig
  unfold pairWeightedStokesMass
  apply Finset.sum_congr rfl
  intro mn hmn
  rw [lowOwnerStokesCorrectedPairWeight_eq_othelloPair hmn]

end RHLean.Proof
