import Mathlib
import «research.GLOBAL_RETURNED_CORE_PAIR_WEIGHTED_OTHELLO_STOKES»

/-!
# Iterated weighted pair Stokes telescope

This file performs the exact iteration that the signed-first route needs.
Starting from an arbitrary finite pair carrier and arbitrary scalar pair weight,
one prime peel is

  mass = boundaryStep + 1/4 * nextInteriorMass.

The boundary step consists only of the two literal coordinate escape faces from
the pair Othello theorem.  The next interior mass carries the mixed Boolean
finite difference of the scalar weight.  Iterating a finite list of prime owners
therefore gives

  initial mass = accumulated signed boundary ledger + terminal signed residual.

No absolute value, square, positivity argument, Schur estimate, or reciprocal
energy appears anywhere in this telescope.
-/

noncomputable section
open scoped BigOperators

namespace RHLean.Proof

attribute [local instance] Classical.propDecidable

/-- Weighted signed pair mass on a finite carrier. -/
def pairWeightedStokesMass
    (C : Finset (ℕ × ℕ)) (f : ℕ × ℕ → ℝ) : ℝ :=
  ∑ mn ∈ C, othelloRealMoebiusPair mn * f mn

/-- Mixed two-coordinate finite difference generated by peeling prime `p`. -/
def pairPrimeMixedDifference
    (p : ℕ) (f : ℕ × ℕ → ℝ) (mn : ℕ × ℕ) : ℝ :=
  (f mn - f (pairPrimeCarrierToggleLeft p mn)) -
    (f (pairPrimeCarrierToggleRight p mn) -
      f (pairPrimeCarrierToggleLeft p
        (pairPrimeCarrierToggleRight p mn)))

/-- The two literal escape faces created by one pair-coordinate peel. -/
def pairWeightedStokesBoundaryStep
    (p : ℕ) (C : Finset (ℕ × ℕ)) (f : ℕ × ℕ → ℝ) : ℝ :=
  (∑ mn ∈ pairPrimeLeftEscapePart p C,
      othelloRealMoebiusPair mn * f mn) +
    (1 / 2 : ℝ) *
      ∑ mn ∈ pairPrimeRightEscapeAfterLeft p C,
        othelloRealMoebiusPair mn *
          (f mn - f (pairPrimeCarrierToggleLeft p mn))

/-- One exact pair Stokes step in compact recurrence form. -/
theorem pairWeightedStokesMass_eq_boundaryStep_add_quarter_interior
    {p : ℕ} (hp : p.Prime) (C : Finset (ℕ × ℕ))
    (f : ℕ × ℕ → ℝ) :
    pairWeightedStokesMass C f =
      pairWeightedStokesBoundaryStep p C f +
        (1 / 4 : ℝ) *
          pairWeightedStokesMass (pairPrimeTwoCoordinateInterior p C)
            (pairPrimeMixedDifference p f) := by
  unfold pairWeightedStokesMass pairWeightedStokesBoundaryStep
    pairPrimeMixedDifference
  exact sum_pairWeightedMoebius_eq_escapeFaces_add_quarter_mixedDifference
    hp C f

/-- Accumulated signed escape ledger after peeling a finite owner list.  Each
later boundary is scaled by the quarter inherited from every preceding complete
pair interior. -/
def iteratedPairWeightedStokesBoundary :
    List ℕ → Finset (ℕ × ℕ) → (ℕ × ℕ → ℝ) → ℝ
  | [], _C, _f => 0
  | p :: ps, C, f =>
      pairWeightedStokesBoundaryStep p C f +
        (1 / 4 : ℝ) *
          iteratedPairWeightedStokesBoundary ps
            (pairPrimeTwoCoordinateInterior p C)
            (pairPrimeMixedDifference p f)

/-- Terminal signed interior after all requested owner peels. -/
def iteratedPairWeightedStokesResidual :
    List ℕ → Finset (ℕ × ℕ) → (ℕ × ℕ → ℝ) → ℝ
  | [], C, f => pairWeightedStokesMass C f
  | p :: ps, C, f =>
      (1 / 4 : ℝ) *
        iteratedPairWeightedStokesResidual ps
          (pairPrimeTwoCoordinateInterior p C)
          (pairPrimeMixedDifference p f)

/-- **Exact iterated weighted pair Stokes theorem.**

After any finite list of prime owner peels, the initial signed mass is exactly
one accumulated signed boundary ledger plus one terminal signed residual.  This
is the abstract `D + B` theorem; all returned-core work downstream should be an
identification of these two exact objects before any inequality is introduced. -/
theorem pairWeightedStokesMass_eq_iteratedBoundary_add_residual :
    ∀ (ps : List ℕ), (∀ p ∈ ps, p.Prime) →
      ∀ (C : Finset (ℕ × ℕ)) (f : ℕ × ℕ → ℝ),
        pairWeightedStokesMass C f =
          iteratedPairWeightedStokesBoundary ps C f +
            iteratedPairWeightedStokesResidual ps C f := by
  intro ps
  induction ps with
  | nil =>
      intro _hprime C f
      simp [iteratedPairWeightedStokesBoundary,
        iteratedPairWeightedStokesResidual]
  | cons p ps ih =>
      intro hprime C f
      have hp : p.Prime := hprime p (by simp)
      have htail : ∀ q ∈ ps, q.Prime := by
        intro q hq
        exact hprime q (by simp [hq])
      have hstep :=
        pairWeightedStokesMass_eq_boundaryStep_add_quarter_interior
          hp C f
      have hrec := ih htail
        (pairPrimeTwoCoordinateInterior p C)
        (pairPrimeMixedDifference p f)
      rw [hstep, hrec]
      simp only [iteratedPairWeightedStokesBoundary,
        iteratedPairWeightedStokesResidual]
      ring

end RHLean.Proof
