import Mathlib
import RHLean.Analysis.PrimeWheelTorusRealization
import RHLean.Analysis.PrimeWheelJointSpectrum
import RHLean.Analysis.PrimeWheelRawPeriod
import RHLean.Proof.SquareRootAncestryRoot
import «research.GLOBAL_RETURNED_CORE_STOKES_CORRECTED_WHEEL_IDENTIFICATION»

/-!
# One corrected finite wheel for the entire Stokes clock

This file is identification only.  It constructs, for every `R >= 2`, a single
finite wheel whose physical block is exactly `(0, X_R]`, where
`X_R = R^2 - 1`, and whose prime coordinates contain every prime through
`sqrt X_R`.

The ambient torus modulus is chosen to be both larger than the physical clock
and a multiple of the complete square-sensitive raw period.  Consequently:

* the corrected site field is exactly Moebius at every physical site;
* the raw seeded comb retains its explicit square-sensitive period;
* every positive endpoint `x <= X_R` is the spectral prefix of the *same*
  corrected joint field.

No conductor estimate, frame inequality, or norm bound appears here.
-/

noncomputable section
open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

open RHLean.Analysis RHLean.Arithmetic
open RHLean.Arithmetic.PrimeWheelFiniteSystem

attribute [local instance] Classical.propDecidable

/-- Natural raw period generated by all square-sensitive prime coordinates on
the physical Stokes clock. -/
def lowOwnerStokesSquareSensitivePeriod (R : ℕ) : ℕ :=
  ∏ p ∈ lowOwnerStokesWheelPrimes R, p ^ 2

/-- The natural raw period is positive. -/
theorem lowOwnerStokesSquareSensitivePeriod_pos (R : ℕ) :
    0 < lowOwnerStokesSquareSensitivePeriod R := by
  unfold lowOwnerStokesSquareSensitivePeriod
  apply Finset.prod_pos
  intro p hp
  exact pow_pos (lowOwnerStokesWheelPrimes_prime hp).pos 2

/-- Every active local square period divides the common raw period. -/
theorem prime_sq_dvd_lowOwnerStokesSquareSensitivePeriod
    {R p : ℕ} (hp : p ∈ lowOwnerStokesWheelPrimes R) :
    p ^ 2 ∣ lowOwnerStokesSquareSensitivePeriod R := by
  unfold lowOwnerStokesSquareSensitivePeriod
  exact Finset.dvd_prod_of_mem (fun q : ℕ => q ^ 2) hp

/-- Common torus modulus: a positive multiple of the complete raw period and
strictly larger than the whole physical clock. -/
def lowOwnerStokesCommonTorusModulus (R : ℕ) : ℕ :=
  (squareRootEndpoint R + 1) * lowOwnerStokesSquareSensitivePeriod R

/-- The common torus modulus is positive. -/
theorem lowOwnerStokesCommonTorusModulus_pos (R : ℕ) :
    0 < lowOwnerStokesCommonTorusModulus R := by
  unfold lowOwnerStokesCommonTorusModulus
  exact Nat.mul_pos (Nat.succ_pos _) (lowOwnerStokesSquareSensitivePeriod_pos R)

/-- For `R >= 2`, the physical completed-square clock is nonempty. -/
theorem squareRootEndpoint_pos_of_two_le
    {R : ℕ} (hR : 2 ≤ R) :
    0 < squareRootEndpoint R := by
  unfold squareRootEndpoint
  apply Nat.sub_pos_of_lt
  nlinarith

/-- The physical clock lies strictly inside the chosen common torus. -/
theorem squareRootEndpoint_lt_lowOwnerStokesCommonTorusModulus
    {R : ℕ} (_hR : 2 ≤ R) :
    squareRootEndpoint R < lowOwnerStokesCommonTorusModulus R := by
  have hP : 1 ≤ lowOwnerStokesSquareSensitivePeriod R :=
    Nat.one_le_iff_ne_zero.mpr
      (Nat.ne_of_gt (lowOwnerStokesSquareSensitivePeriod_pos R))
  calc
    squareRootEndpoint R < squareRootEndpoint R + 1 := Nat.lt_succ_self _
    _ ≤ (squareRootEndpoint R + 1) *
        lowOwnerStokesSquareSensitivePeriod R := by
      simpa using Nat.mul_le_mul_left (squareRootEndpoint R + 1) hP
    _ = lowOwnerStokesCommonTorusModulus R := rfl

/-- One finite corrected wheel carrying the entire physical Stokes clock. -/
def lowOwnerStokesWheelSystem (R : ℕ) (hR : 2 ≤ R) :
    PrimeWheelFiniteSystem where
  lower := 0
  upper := squareRootEndpoint R
  modulus := lowOwnerStokesCommonTorusModulus R
  lower_lt_upper := squareRootEndpoint_pos_of_two_le hR
  modulus_pos := lowOwnerStokesCommonTorusModulus_pos R
  upper_lt_modulus :=
    squareRootEndpoint_lt_lowOwnerStokesCommonTorusModulus hR
  primeCoordinates := lowOwnerStokesWheelPrimes R
  primeCoordinates_prime := by
    intro p hp
    exact lowOwnerStokesWheelPrimes_prime hp

/-- The raw site field of the arbitrary-clock wheel has the complete
square-sensitive period. -/
theorem lowOwnerStokesWheelRawSite_periodic
    (R : ℕ) (_hR : 2 ≤ R) :
    Function.Periodic
      (lowOwnerStokesWheelSystem R _hR).rawSite
      (lowOwnerStokesSquareSensitivePeriod R) := by
  simpa [PrimeWheelFiniteSystem.rawSite, lowOwnerStokesWheelSystem] using
    (seededPrimeComb_periodic_of_squarePeriods_dvd
      (lowOwnerStokesWheelPrimes R)
      (lowOwnerStokesSquareSensitivePeriod R)
      (fun p hp => prime_sq_dvd_lowOwnerStokesSquareSensitivePeriod hp))

/-- Exact arithmetic certificate: the corrected field is Moebius on the entire
physical clock. -/
def lowOwnerStokesWheelArithmeticCertificate
    (R : ℕ) (hR : 2 ≤ R) :
    (lowOwnerStokesWheelSystem R hR).ArithmeticCertificate where
  corrected_eq_moebius := by
    intro n hnpos hnupper
    change correctedPrimeWheelSite
      (lowOwnerStokesWheelPrimes R) (squareRootEndpoint R) n = μ n
    exact correctedPrimeWheelSite_eq_moebius
      (lowOwnerStokesWheelPrimes R)
      (fun p hp => lowOwnerStokesWheelPrimes_prime hp)
      (lowOwnerStokesWheelPrimes_sqrtCoverage R)
      hnpos hnupper

/-- The pinned interval `(0,x]` is exactly the positive integer interval
`[1,x]`. -/
theorem lowOwnerStokesWheel_prefixInterval_eq_Icc
    (R : ℕ) (hR : 2 ≤ R) (x : ℕ) :
    (lowOwnerStokesWheelSystem R hR).prefixInterval x =
      Finset.Icc 1 x := by
  ext n
  simp [PrimeWheelFiniteSystem.prefixInterval, lowOwnerStokesWheelSystem]
  omega

/-- The arithmetic residual of the common Stokes wheel is exactly the integer
Mertens prefix at every endpoint inside the clock. -/
theorem lowOwnerStokesWheel_residual_eq_mertensSummatoryInt
    {R x : ℕ} (hR : 2 ≤ R)
    (hx : x ≤ squareRootEndpoint R) :
    (lowOwnerStokesWheelSystem R hR).residual x =
      mertensSummatoryInt x := by
  rw [(lowOwnerStokesWheelSystem R hR).residual_eq_moebius_sum
    (lowOwnerStokesWheelArithmeticCertificate R hR) hx]
  rw [lowOwnerStokesWheel_prefixInterval_eq_Icc,
    ← mertensSummatoryInt_eq_Icc]

/-- **Common corrected-spectrum representation of every positive Stokes
endpoint.**  All endpoints use the same corrected joint spectrum; only the
prefix window changes. -/
theorem lowOwnerStokesWheel_spectralPrefix_eq_mertensSummatory
    {R x : ℕ} (hR : 2 ≤ R)
    (hxpos : 0 < x) (hx : x ≤ squareRootEndpoint R) :
    (lowOwnerStokesWheelSystem R hR).spectralPrefix x =
      mertensSummatory x := by
  calc
    (lowOwnerStokesWheelSystem R hR).spectralPrefix x =
        (((lowOwnerStokesWheelSystem R hR).residual x : ℤ) : ℂ) := by
      exact (lowOwnerStokesWheelSystem R hR).spectralPrefix_eq_residual
        (lowOwnerStokesWheelSystem R hR).canonicalTorusRealizationCertificate
        hxpos hx
    _ = ((mertensSummatoryInt x : ℤ) : ℂ) := by
      rw [lowOwnerStokesWheel_residual_eq_mertensSummatoryInt hR hx]
    _ = mertensSummatory x := mertensSummatoryInt_cast x

end RHLean.Proof
