import Mathlib
import «research.GLOBAL_RETURNED_CORE_STOKES_BOUNDARY_IDENTIFICATION»
import «research.GLOBAL_RETURNED_CORE_STOKES_TERMINAL_CLASSIFICATION»

/-!
# One-dimensional amplitude factorization of Stokes clip steps

The Stokes scalar entering one first-owner cell is not a generic pair weight.
It is a symmetric cross form

  Cross(L,J)(a,b) = -L(a)J(b) - J(a)L(b).

A mixed prime difference preserves that form, replacing L,J by their
one-dimensional toggle differences.  Consequently the exact two-coordinate
Stokes step can be evaluated entirely in signed one-dimensional amplitudes
before any estimate is made.

No absolute value, packetwise square, or owner-count bound appears here.
-/

noncomputable section
open scoped BigOperators

namespace RHLean.Proof

open RHLean.Analysis RHLean.Arithmetic

attribute [local instance] Classical.propDecidable

/-- Symmetric cross scalar generated by two one-dimensional coefficient fields. -/
def lowOwnerStokesCrossScalar
    (L J : ℕ → ℝ) (mn : ℕ × ℕ) : ℝ :=
  -(L mn.1 * J mn.2) - J mn.1 * L mn.2

/-- One-dimensional multiplicative toggle difference. -/
def lowOwnerStokesToggleDifference
    (r : ℕ) (f : ℕ → ℝ) (n : ℕ) : ℝ :=
  f n - f (primeCarrierToggle r n)

/-- The physical first-owner polarization scalar is exactly a cross scalar. -/
theorem lowOwnerFirstOwnerDirichletPolarizationScalar_eq_cross
    (R p : ℕ) :
    lowOwnerFirstOwnerDirichletPolarizationScalar R p =
      lowOwnerStokesCrossScalar
        (lowOwnerDirichletBaseCoefficient R)
        (lowOwnerDirichletReturnedCoefficient R p) := by
  funext mn
  rcases mn with ⟨a, b⟩
  unfold lowOwnerFirstOwnerDirichletPolarizationScalar
    lowOwnerStokesCrossScalar
    lowOwnerDirichletIncidenceCoefficient
  ring

/-- **Cross-form closure under a mixed prime difference.** -/
theorem pairPrimeMixedDifference_crossScalar
    (r : ℕ) (L J : ℕ → ℝ) :
    pairPrimeMixedDifference r (lowOwnerStokesCrossScalar L J) =
      lowOwnerStokesCrossScalar
        (lowOwnerStokesToggleDifference r L)
        (lowOwnerStokesToggleDifference r J) := by
  funext mn
  rcases mn with ⟨a, b⟩
  unfold pairPrimeMixedDifference
    pairPrimeCarrierToggleLeft pairPrimeCarrierToggleRight
    lowOwnerStokesCrossScalar lowOwnerStokesToggleDifference
  simp only
  ring

/-- Signed one-dimensional amplitude on an arbitrary finite carrier. -/
def lowOwnerStokesSignedAmplitude
    (S : Finset ℕ) (f : ℕ → ℝ) : ℝ :=
  ∑ n ∈ S, othelloRealMoebius n * f n

private theorem sum_product_othello_separable
    (S T : Finset ℕ) (g h : ℕ → ℝ) :
    (∑ mn ∈ S.product T,
      othelloRealMoebiusPair mn * (g mn.1 * h mn.2)) =
      lowOwnerStokesSignedAmplitude S g *
        lowOwnerStokesSignedAmplitude T h := by
  unfold lowOwnerStokesSignedAmplitude
    othelloRealMoebiusPair
  calc
    (∑ mn ∈ S.product T,
      (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
        (g mn.1 * h mn.2)) =
      ∑ a ∈ S, ∑ b ∈ T,
        (othelloRealMoebius a * othelloRealMoebius b) * (g a * h b) := by
          simpa only using
            (Finset.sum_product
              (s := S) (t := T)
              (f := fun mn : ℕ × ℕ =>
                (othelloRealMoebius mn.1 * othelloRealMoebius mn.2) *
                  (g mn.1 * h mn.2)))
    _ = ∑ a ∈ S,
        (othelloRealMoebius a * g a) *
          (∑ b ∈ T, othelloRealMoebius b * h b) := by
        apply Finset.sum_congr rfl
        intro a _ha
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro b _hb
        ring
    _ = (∑ a ∈ S, othelloRealMoebius a * g a) *
        (∑ b ∈ T, othelloRealMoebius b * h b) := by
      rw [Finset.sum_mul]

/-- A cross scalar on a Cartesian product factors exactly into two signed
one-dimensional amplitude products. -/
theorem pairWeightedStokesMass_product_crossScalar
    (A B : Finset ℕ) (L J : ℕ → ℝ) :
    pairWeightedStokesMass (A.product B) (lowOwnerStokesCrossScalar L J) =
      -(lowOwnerStokesSignedAmplitude A L *
          lowOwnerStokesSignedAmplitude B J) -
        lowOwnerStokesSignedAmplitude A J *
          lowOwnerStokesSignedAmplitude B L := by
  unfold pairWeightedStokesMass lowOwnerStokesCrossScalar
  calc
    (∑ mn ∈ A.product B,
      othelloRealMoebiusPair mn *
        (-(L mn.1 * J mn.2) - J mn.1 * L mn.2)) =
      ∑ mn ∈ A.product B,
        (-(othelloRealMoebiusPair mn * (L mn.1 * J mn.2)) -
          othelloRealMoebiusPair mn * (J mn.1 * L mn.2)) := by
            apply Finset.sum_congr rfl
            intro mn _hmn
            ring
    _ =
      -(∑ mn ∈ A.product B,
          othelloRealMoebiusPair mn * (L mn.1 * J mn.2)) -
        (∑ mn ∈ A.product B,
          othelloRealMoebiusPair mn * (J mn.1 * L mn.2)) := by
            rw [Finset.sum_sub_distrib, Finset.sum_neg_distrib]
    _ = _ := by
      rw [sum_product_othello_separable, sum_product_othello_separable]

/-- **Exact amplitude form of one Stokes boundary step.**

The entire pair escape ledger is the current cross amplitude minus one quarter
of the next complete-interior cross amplitude.  After cross factorization this
is just

  -2 B J + (1/2) (Delta B)_int (Delta J)_int.
-/
theorem pairWeightedStokesBoundaryStep_product_crossScalar
    {r : ℕ} (hr : r.Prime) (A : Finset ℕ) (L J : ℕ → ℝ) :
    pairWeightedStokesBoundaryStep r (A.product A)
        (lowOwnerStokesCrossScalar L J) =
      -2 * lowOwnerStokesSignedAmplitude A L *
          lowOwnerStokesSignedAmplitude A J +
        (1 / 2 : ℝ) *
          lowOwnerStokesSignedAmplitude (primeInteriorPart r A)
            (lowOwnerStokesToggleDifference r L) *
          lowOwnerStokesSignedAmplitude (primeInteriorPart r A)
            (lowOwnerStokesToggleDifference r J) := by
  have hstep :=
    pairWeightedStokesMass_eq_boundaryStep_add_quarter_interior
      hr (A.product A) (lowOwnerStokesCrossScalar L J)
  rw [pairPrimeTwoCoordinateInterior_product] at hstep
  rw [pairPrimeMixedDifference_crossScalar] at hstep
  rw [pairWeightedStokesMass_product_crossScalar,
    pairWeightedStokesMass_product_crossScalar] at hstep
  ring_nf at hstep ⊢
  linarith

/-- Specialization to one literal first-owner Stokes cell.  The pair boundary
is now expressed wholly through one-dimensional signed amplitudes. -/
theorem lowOwnerFirstOwner_pairBoundaryStep_eq_signedAmplitudeProducts
    {R p r : ℕ} {sig : Finset ℕ} (hr : r.Prime) :
    pairWeightedStokesBoundaryStep r
        (lowOwnerFirstOwnerSignedCellPairCarrier R p sig)
        (lowOwnerFirstOwnerDirichletPolarizationScalar R p) =
      -2 *
        lowOwnerStokesSignedAmplitude
          (lowOwnerFirstOwnerBaseFiber R p sig)
          (lowOwnerDirichletBaseCoefficient R) *
        lowOwnerStokesSignedAmplitude
          (lowOwnerFirstOwnerBaseFiber R p sig)
          (lowOwnerDirichletReturnedCoefficient R p) +
      (1 / 2 : ℝ) *
        lowOwnerStokesSignedAmplitude
          (primeInteriorPart r (lowOwnerFirstOwnerBaseFiber R p sig))
          (lowOwnerStokesToggleDifference r
            (lowOwnerDirichletBaseCoefficient R)) *
        lowOwnerStokesSignedAmplitude
          (primeInteriorPart r (lowOwnerFirstOwnerBaseFiber R p sig))
          (lowOwnerStokesToggleDifference r
            (lowOwnerDirichletReturnedCoefficient R p)) := by
  unfold lowOwnerFirstOwnerSignedCellPairCarrier
  rw [lowOwnerFirstOwnerDirichletPolarizationScalar_eq_cross]
  exact pairWeightedStokesBoundaryStep_product_crossScalar
    hr (lowOwnerFirstOwnerBaseFiber R p sig)
      (lowOwnerDirichletBaseCoefficient R)
      (lowOwnerDirichletReturnedCoefficient R p)


/-! ## Exceptional terminal amplitudes in the same currency -/

/-- Empty remaining schedule: the terminal term is exactly the original
assembled base/returned cross amplitude of the cell. -/
theorem lowOwnerFirstOwnerTopTerminal_eq_neg_two_base_mul_returned_of_schedule_nil
    {R p : ℕ} {sig : Finset ℕ}
    (_hp : p.Prime)
    (hps : lowOwnerFirstOwnerCanonicalStokesSchedule R p = []) :
    lowOwnerFirstOwnerCanonicalStokesTopTerminalBoundary R p sig =
      -2 * lowOwnerFirstOwnerBaseAmplitude R p sig *
        lowOwnerFirstOwnerReturnedChildParentAmplitude R p sig := by
  simp only [lowOwnerFirstOwnerCanonicalStokesTopTerminalBoundary, hps]
  unfold lowOwnerFirstOwnerSignedCellPairCarrier
  rw [lowOwnerFirstOwnerDirichletPolarizationScalar_eq_cross]
  rw [pairWeightedStokesMass_product_crossScalar]
  have hbase :
      lowOwnerStokesSignedAmplitude
          (lowOwnerFirstOwnerBaseFiber R p sig)
          (lowOwnerDirichletBaseCoefficient R) =
        lowOwnerFirstOwnerBaseAmplitude R p sig := by
    simpa [lowOwnerStokesSignedAmplitude, lowOwnerDirichletBaseCoefficient,
      lowOwnerFirstOwnerDirichletBaseSite, othelloRealMoebius,
      RHLean.Analysis.realMoebiusStep, mul_comm] using
        (sum_lowOwnerFirstOwnerDirichletBaseSite_eq_amplitude R p sig)
  have hret :
      lowOwnerStokesSignedAmplitude
          (lowOwnerFirstOwnerBaseFiber R p sig)
          (lowOwnerDirichletReturnedCoefficient R p) =
        lowOwnerFirstOwnerReturnedChildParentAmplitude R p sig := by
    simpa [lowOwnerStokesSignedAmplitude, lowOwnerDirichletReturnedCoefficient,
      lowOwnerFirstOwnerDirichletReturnedChildSite, othelloRealMoebius,
      RHLean.Analysis.realMoebiusStep, mul_comm] using
        (sum_lowOwnerFirstOwnerDirichletReturnedChildSite_eq_returned
          (R := R) (p := p) (sig := sig))
  rw [hbase, hret]
  ring

/-- **Assembled empty-schedule factorization.**  Signatures are summed only
after the exact cross product has been formed in each cell; no cellwise
magnitude is introduced. -/
theorem sum_lowOwnerFirstOwnerTopTerminal_eq_neg_two_base_mul_returned_of_schedule_nil
    {R p : ℕ}
    (hp : p.Prime)
    (hps : lowOwnerFirstOwnerCanonicalStokesSchedule R p = []) :
    (∑ sig ∈ lowOwnerFirstOwnerSignatureSet R p,
      lowOwnerFirstOwnerCanonicalStokesTopTerminalBoundary R p sig) =
      ∑ sig ∈ lowOwnerFirstOwnerSignatureSet R p,
        (-2 * lowOwnerFirstOwnerBaseAmplitude R p sig *
          lowOwnerFirstOwnerReturnedChildParentAmplitude R p sig) := by
  apply Finset.sum_congr rfl
  intro sig _hsig
  exact
    lowOwnerFirstOwnerTopTerminal_eq_neg_two_base_mul_returned_of_schedule_nil
      hp hps

/-- One remaining owner: the exact quarter-weighted terminal packet is already
one half of an interior base/returned difference product.  This is the literal
Stokes quarter factor after cross-amplitude factorization. -/
theorem lowOwnerFirstOwnerTopTerminal_eq_neg_half_interiorDifferenceProduct_of_schedule_single
    {R p q : ℕ} {sig : Finset ℕ}
    (hps : lowOwnerFirstOwnerCanonicalStokesSchedule R p = [q]) :
    lowOwnerFirstOwnerCanonicalStokesTopTerminalBoundary R p sig =
      -(1 / 2 : ℝ) *
        lowOwnerStokesSignedAmplitude
          (primeInteriorPart q (lowOwnerFirstOwnerBaseFiber R p sig))
          (lowOwnerStokesToggleDifference q
            (lowOwnerDirichletBaseCoefficient R)) *
        lowOwnerStokesSignedAmplitude
          (primeInteriorPart q (lowOwnerFirstOwnerBaseFiber R p sig))
          (lowOwnerStokesToggleDifference q
            (lowOwnerDirichletReturnedCoefficient R p)) := by
  simp only [lowOwnerFirstOwnerCanonicalStokesTopTerminalBoundary, hps]
  unfold lowOwnerFirstOwnerSignedCellPairCarrier
  rw [pairPrimeTwoCoordinateInterior_product]
  rw [lowOwnerFirstOwnerDirichletPolarizationScalar_eq_cross]
  rw [pairPrimeMixedDifference_crossScalar]
  rw [pairWeightedStokesMass_product_crossScalar]
  ring

/-- **Assembled one-owner terminal factorization.**  The exact quarter-weighted
mixed difference remains assembled over signatures. -/
theorem sum_lowOwnerFirstOwnerTopTerminal_eq_neg_half_interiorDifferenceProduct_of_schedule_single
    {R p q : ℕ}
    (hps : lowOwnerFirstOwnerCanonicalStokesSchedule R p = [q]) :
    (∑ sig ∈ lowOwnerFirstOwnerSignatureSet R p,
      lowOwnerFirstOwnerCanonicalStokesTopTerminalBoundary R p sig) =
      ∑ sig ∈ lowOwnerFirstOwnerSignatureSet R p,
        (-(1 / 2 : ℝ) *
          lowOwnerStokesSignedAmplitude
            (primeInteriorPart q (lowOwnerFirstOwnerBaseFiber R p sig))
            (lowOwnerStokesToggleDifference q
              (lowOwnerDirichletBaseCoefficient R)) *
          lowOwnerStokesSignedAmplitude
            (primeInteriorPart q (lowOwnerFirstOwnerBaseFiber R p sig))
            (lowOwnerStokesToggleDifference q
              (lowOwnerDirichletReturnedCoefficient R p))) := by
  apply Finset.sum_congr rfl
  intro sig _hsig
  exact
    lowOwnerFirstOwnerTopTerminal_eq_neg_half_interiorDifferenceProduct_of_schedule_single
      hps

end RHLean.Proof
