import Mathlib
import «research.GLOBAL_RETURNED_CORE_STOKES_ZERO_TARGET_COVARIANCE»
import «research.ZERO_TARGET_MELLIN_COMPLETE_POST_ROOT_CUBES»
import «research.ZERO_TARGET_CLIPPED_OWNER_ENERGY_CONTRACTION»

/-!
# Normalized NNS zero-target covariance on the physical Stokes carrier

The repository already has Fred's target-zero partial-moment decomposition

  co_0(x,y) - div_0(x,y) = x*y

and the exact FinalStokes identity

  FinalStokes_R = 2 * (CoCross_R - DivCross_R).

This file adds the normalization used by NNS: divide the signed target-zero
excess by the total target-zero pair mass.  No mean centering is introduced.

It then applies the same normalization to the literal complete post-root
Mellin four-corner population.  Since the complete-cube numerator is already
proved nonpositive, its normalized covariance is nonpositive as well.  Thus a
positive normalized covariance mode cannot be generated by complete fresh-prime
cubes; the only remaining positive physical exit is the already-isolated
clipped channel, whose outgoing energy has the compiled 79/81 contraction.

No RH assumption or Mertens magnitude estimate is used.
-/

noncomputable section
open scoped BigOperators

namespace RHLean.Proof

open RHLean.Analysis RHLean.Arithmetic

attribute [local instance] Classical.propDecidable

/-! ## Generic NNS target-zero normalization -/

/-- NNS-style normalized target-zero covariance from nonnegative co-partial and
divergent masses.  The zero-total convention is zero. -/
def nnsZeroTargetNormalizedCovariance (co div : ℝ) : ℝ :=
  if co + div = 0 then 0 else (co - div) / (co + div)

private theorem zeroTargetUpperPart_nonneg_local (x : ℝ) :
    0 ≤ zeroTargetUpperPart x := by
  unfold zeroTargetUpperPart
  nlinarith [neg_abs_le x]

private theorem zeroTargetLowerPart_nonneg_local (x : ℝ) :
    0 ≤ zeroTargetLowerPart x := by
  unfold zeroTargetLowerPart
  nlinarith [le_abs_self x]

theorem zeroTargetCoPartialPair_nonneg (x y : ℝ) :
    0 ≤ zeroTargetCoPartialPair x y := by
  unfold zeroTargetCoPartialPair zeroTargetCLPM zeroTargetCUPM
  exact add_nonneg
    (mul_nonneg (zeroTargetLowerPart_nonneg_local x)
      (zeroTargetLowerPart_nonneg_local y))
    (mul_nonneg (zeroTargetUpperPart_nonneg_local x)
      (zeroTargetUpperPart_nonneg_local y))

theorem zeroTargetDivergentPair_nonneg (x y : ℝ) :
    0 ≤ zeroTargetDivergentPair x y := by
  unfold zeroTargetDivergentPair zeroTargetDLPM zeroTargetDUPM
  exact add_nonneg
    (mul_nonneg (zeroTargetLowerPart_nonneg_local x)
      (zeroTargetUpperPart_nonneg_local y))
    (mul_nonneg (zeroTargetUpperPart_nonneg_local x)
      (zeroTargetLowerPart_nonneg_local y))

theorem nnsZeroTargetNormalizedCovariance_bounds
    {co div : ℝ} (hco : 0 ≤ co) (hdiv : 0 ≤ div) :
    -1 ≤ nnsZeroTargetNormalizedCovariance co div ∧
      nnsZeroTargetNormalizedCovariance co div ≤ 1 := by
  by_cases hzero : co + div = 0
  · simp [nnsZeroTargetNormalizedCovariance, hzero]
  · have hden : 0 < co + div :=
      lt_of_le_of_ne (add_nonneg hco hdiv) (Ne.symm hzero)
    constructor
    · rw [nnsZeroTargetNormalizedCovariance, if_neg hzero]
      apply (le_div_iff₀ hden).2
      linarith
    · rw [nnsZeroTargetNormalizedCovariance, if_neg hzero]
      apply (div_le_iff₀ hden).2
      linarith

theorem nnsZeroTargetNormalizedCovariance_mul_total
    {co div : ℝ} (hco : 0 ≤ co) (hdiv : 0 ≤ div) :
    nnsZeroTargetNormalizedCovariance co div * (co + div) = co - div := by
  by_cases hzero : co + div = 0
  · have hco0 : co = 0 := by nlinarith
    have hdiv0 : div = 0 := by nlinarith
    simp [nnsZeroTargetNormalizedCovariance, hzero, hco0, hdiv0]
  · rw [nnsZeroTargetNormalizedCovariance, if_neg hzero]
    field_simp

theorem nnsZeroTargetNormalizedCovariance_nonpos_iff
    {co div : ℝ} (hco : 0 ≤ co) (hdiv : 0 ≤ div) :
    nnsZeroTargetNormalizedCovariance co div ≤ 0 ↔ co ≤ div := by
  by_cases hzero : co + div = 0
  · have hco0 : co = 0 := by nlinarith
    have hdiv0 : div = 0 := by nlinarith
    simp [nnsZeroTargetNormalizedCovariance, hzero, hco0, hdiv0]
  · have hden : 0 < co + div :=
      lt_of_le_of_ne (add_nonneg hco hdiv) (Ne.symm hzero)
    rw [nnsZeroTargetNormalizedCovariance, if_neg hzero]
    constructor
    · intro h
      have hnum : co - div ≤ 0 := by
        have h' := (div_le_iff₀ hden).mp h
        simpa using h'
      linarith
    · intro h
      apply (div_le_iff₀ hden).2
      simp
      linarith

/-! ## Exact normalization of the actual FinalStokes carrier -/

def lowOwnerStokesZeroTargetCoMass (R : ℕ) : ℝ :=
  zeroTargetCoPartialCross
    (lowOwnerZeroFrequencyMobiusSite R)
    (squareRootEndpoint R + 1)

def lowOwnerStokesZeroTargetDivergentMass (R : ℕ) : ℝ :=
  zeroTargetDivergentCross
    (lowOwnerZeroFrequencyMobiusSite R)
    (squareRootEndpoint R + 1)

def lowOwnerStokesZeroTargetTotalMass (R : ℕ) : ℝ :=
  lowOwnerStokesZeroTargetCoMass R +
    lowOwnerStokesZeroTargetDivergentMass R

def lowOwnerStokesNNSNormalizedCovariance (R : ℕ) : ℝ :=
  nnsZeroTargetNormalizedCovariance
    (lowOwnerStokesZeroTargetCoMass R)
    (lowOwnerStokesZeroTargetDivergentMass R)

theorem zeroTargetCoPartialCross_nonneg (B : ℕ → ℝ) (K : ℕ) :
    0 ≤ zeroTargetCoPartialCross B K := by
  unfold zeroTargetCoPartialCross
  apply Finset.sum_nonneg
  intro j _hj
  apply Finset.sum_nonneg
  intro i _hi
  exact zeroTargetCoPartialPair_nonneg _ _

theorem zeroTargetDivergentCross_nonneg (B : ℕ → ℝ) (K : ℕ) :
    0 ≤ zeroTargetDivergentCross B K := by
  unfold zeroTargetDivergentCross
  apply Finset.sum_nonneg
  intro j _hj
  apply Finset.sum_nonneg
  intro i _hi
  exact zeroTargetDivergentPair_nonneg _ _

theorem lowOwnerStokesNNSNormalizedCovariance_bounds (R : ℕ) :
    -1 ≤ lowOwnerStokesNNSNormalizedCovariance R ∧
      lowOwnerStokesNNSNormalizedCovariance R ≤ 1 := by
  apply nnsZeroTargetNormalizedCovariance_bounds
  · exact zeroTargetCoPartialCross_nonneg _ _
  · exact zeroTargetDivergentCross_nonneg _ _

theorem lowOwnerStokesNNSNormalizedCovariance_mul_total (R : ℕ) :
    lowOwnerStokesNNSNormalizedCovariance R *
        lowOwnerStokesZeroTargetTotalMass R =
      lowOwnerStokesZeroTargetCoMass R -
        lowOwnerStokesZeroTargetDivergentMass R := by
  apply nnsZeroTargetNormalizedCovariance_mul_total
  · exact zeroTargetCoPartialCross_nonneg _ _
  · exact zeroTargetDivergentCross_nonneg _ _

/-- **Normalized NNS form of FinalStokes.**

The entire signed Stokes boundary is one dimensionless target-zero covariance
coefficient in [-1,1] times the total target-zero pair mass. -/
theorem lowOwnerCanonicalSignedStokesFinalBoundary_eq_two_nnsNormalized_mul_total
    {R : ℕ} (hR : 2 ≤ R) :
    lowOwnerCanonicalSignedStokesFinalBoundary R =
      2 * lowOwnerStokesNNSNormalizedCovariance R *
        lowOwnerStokesZeroTargetTotalMass R := by
  rw [lowOwnerCanonicalSignedStokesFinalBoundary_eq_two_zeroTargetCrossExcess hR]
  have hnorm := lowOwnerStokesNNSNormalizedCovariance_mul_total R
  unfold lowOwnerStokesZeroTargetCoMass
    lowOwnerStokesZeroTargetDivergentMass
    lowOwnerStokesZeroTargetTotalMass at hnorm ⊢
  nlinarith

theorem lowOwnerStokesNNSNormalizedCovariance_nonpos_iff (R : ℕ) :
    lowOwnerStokesNNSNormalizedCovariance R ≤ 0 ↔
      lowOwnerStokesZeroTargetCoMass R ≤
        lowOwnerStokesZeroTargetDivergentMass R := by
  apply nnsZeroTargetNormalizedCovariance_nonpos_iff
  · exact zeroTargetCoPartialCross_nonneg _ _
  · exact zeroTargetDivergentCross_nonneg _ _

/-! ## Literal NNS co/div split of one physical Mellin four-corner cube -/

private theorem physicalSuperLcmIndicator_nonneg_local (W a b : ℕ) :
    0 ≤ physicalSuperLcmIndicator W a b := by
  by_cases hab : a ≤ W ∧ b ≤ W
  · by_cases hL : W < Nat.lcm a b
    · simp [physicalSuperLcmIndicator, superLcmIndicator, hab, hL]
    · simp [physicalSuperLcmIndicator, superLcmIndicator, hab, hL]
  · simp [physicalSuperLcmIndicator, hab]

def zeroTargetMellinPhysicalSuperLcmFourCornerCo
    (W p : ℕ) (r : ℝ) (a b : ℕ) : ℝ :=
  zeroTargetCoPartialPair (realMoebiusStep a) (realMoebiusStep b) *
      physicalSuperLcmIndicator W a b +
    zeroTargetCoPartialPair (r * realMoebiusStep (p * a)) (realMoebiusStep b) *
      physicalSuperLcmIndicator W (p * a) b +
    zeroTargetCoPartialPair (realMoebiusStep a) (r * realMoebiusStep (p * b)) *
      physicalSuperLcmIndicator W a (p * b) +
    zeroTargetCoPartialPair (r * realMoebiusStep (p * a))
        (r * realMoebiusStep (p * b)) *
      physicalSuperLcmIndicator W (p * a) (p * b)

def zeroTargetMellinPhysicalSuperLcmFourCornerDiv
    (W p : ℕ) (r : ℝ) (a b : ℕ) : ℝ :=
  zeroTargetDivergentPair (realMoebiusStep a) (realMoebiusStep b) *
      physicalSuperLcmIndicator W a b +
    zeroTargetDivergentPair (r * realMoebiusStep (p * a)) (realMoebiusStep b) *
      physicalSuperLcmIndicator W (p * a) b +
    zeroTargetDivergentPair (realMoebiusStep a) (r * realMoebiusStep (p * b)) *
      physicalSuperLcmIndicator W a (p * b) +
    zeroTargetDivergentPair (r * realMoebiusStep (p * a))
        (r * realMoebiusStep (p * b)) *
      physicalSuperLcmIndicator W (p * a) (p * b)

theorem zeroTargetMellinPhysicalSuperLcmFourCornerCo_nonneg
    (W p : ℕ) (r : ℝ) (a b : ℕ) :
    0 ≤ zeroTargetMellinPhysicalSuperLcmFourCornerCo W p r a b := by
  unfold zeroTargetMellinPhysicalSuperLcmFourCornerCo
  have h00 := mul_nonneg (zeroTargetCoPartialPair_nonneg
      (realMoebiusStep a) (realMoebiusStep b))
    (physicalSuperLcmIndicator_nonneg_local W a b)
  have h10 := mul_nonneg (zeroTargetCoPartialPair_nonneg
      (r * realMoebiusStep (p * a)) (realMoebiusStep b))
    (physicalSuperLcmIndicator_nonneg_local W (p * a) b)
  have h01 := mul_nonneg (zeroTargetCoPartialPair_nonneg
      (realMoebiusStep a) (r * realMoebiusStep (p * b)))
    (physicalSuperLcmIndicator_nonneg_local W a (p * b))
  have h11 := mul_nonneg (zeroTargetCoPartialPair_nonneg
      (r * realMoebiusStep (p * a)) (r * realMoebiusStep (p * b)))
    (physicalSuperLcmIndicator_nonneg_local W (p * a) (p * b))
  linarith

theorem zeroTargetMellinPhysicalSuperLcmFourCornerDiv_nonneg
    (W p : ℕ) (r : ℝ) (a b : ℕ) :
    0 ≤ zeroTargetMellinPhysicalSuperLcmFourCornerDiv W p r a b := by
  unfold zeroTargetMellinPhysicalSuperLcmFourCornerDiv
  have h00 := mul_nonneg (zeroTargetDivergentPair_nonneg
      (realMoebiusStep a) (realMoebiusStep b))
    (physicalSuperLcmIndicator_nonneg_local W a b)
  have h10 := mul_nonneg (zeroTargetDivergentPair_nonneg
      (r * realMoebiusStep (p * a)) (realMoebiusStep b))
    (physicalSuperLcmIndicator_nonneg_local W (p * a) b)
  have h01 := mul_nonneg (zeroTargetDivergentPair_nonneg
      (realMoebiusStep a) (r * realMoebiusStep (p * b)))
    (physicalSuperLcmIndicator_nonneg_local W a (p * b))
  have h11 := mul_nonneg (zeroTargetDivergentPair_nonneg
      (r * realMoebiusStep (p * a)) (r * realMoebiusStep (p * b)))
    (physicalSuperLcmIndicator_nonneg_local W (p * a) (p * b))
  linarith

theorem zeroTargetMellinPhysicalSuperLcmFourCorner_eq_co_sub_div
    {W p a b : ℕ} {r : ℝ} (hr : 0 ≤ r)
    (hp : p.Prime) (hpa : ¬ p ∣ a) (hpb : ¬ p ∣ b) :
    zeroTargetMellinPhysicalSuperLcmFourCorner W p r a b =
      zeroTargetMellinPhysicalSuperLcmFourCornerCo W p r a b -
        zeroTargetMellinPhysicalSuperLcmFourCornerDiv W p r a b := by
  rw [zeroTargetMellinPhysicalSuperLcmFourCorner_eq_weighted_excess_corners
    hr hp hpa hpb]
  unfold postRootZeroTargetPairExcess zeroTargetPairExcess
    zeroTargetMellinPhysicalSuperLcmFourCornerCo
    zeroTargetMellinPhysicalSuperLcmFourCornerDiv
  ring

/-! ## Complete post-root population: normalized covariance is nonpositive -/

def zeroTargetMellinCompletePostRootCo
    (W : ℕ) (r : ℕ → ℝ) : ℝ :=
  ∑ p ∈ postRootPrimeFamilySet W,
    ∑ mn ∈ mertensPositivePhysicalPairCarrier (W / p),
      zeroTargetMellinPhysicalSuperLcmFourCornerCo W p (r p) mn.1 mn.2

def zeroTargetMellinCompletePostRootDiv
    (W : ℕ) (r : ℕ → ℝ) : ℝ :=
  ∑ p ∈ postRootPrimeFamilySet W,
    ∑ mn ∈ mertensPositivePhysicalPairCarrier (W / p),
      zeroTargetMellinPhysicalSuperLcmFourCornerDiv W p (r p) mn.1 mn.2

def zeroTargetMellinCompletePostRootNNSNormalized
    (W : ℕ) (r : ℕ → ℝ) : ℝ :=
  nnsZeroTargetNormalizedCovariance
    (zeroTargetMellinCompletePostRootCo W r)
    (zeroTargetMellinCompletePostRootDiv W r)

theorem zeroTargetMellinCompletePostRootCo_nonneg
    (W : ℕ) (r : ℕ → ℝ) :
    0 ≤ zeroTargetMellinCompletePostRootCo W r := by
  unfold zeroTargetMellinCompletePostRootCo
  apply Finset.sum_nonneg
  intro p _hp
  apply Finset.sum_nonneg
  intro mn _hmn
  exact zeroTargetMellinPhysicalSuperLcmFourCornerCo_nonneg _ _ _ _ _

theorem zeroTargetMellinCompletePostRootDiv_nonneg
    (W : ℕ) (r : ℕ → ℝ) :
    0 ≤ zeroTargetMellinCompletePostRootDiv W r := by
  unfold zeroTargetMellinCompletePostRootDiv
  apply Finset.sum_nonneg
  intro p _hp
  apply Finset.sum_nonneg
  intro mn _hmn
  exact zeroTargetMellinPhysicalSuperLcmFourCornerDiv_nonneg _ _ _ _ _

theorem sum_all_zeroTargetMellinCompletePostRootFamilies_eq_co_sub_div
    (W : ℕ) (r : ℕ → ℝ)
    (hr0 : ∀ p ∈ postRootPrimeFamilySet W, 0 ≤ r p) :
    (∑ p ∈ postRootPrimeFamilySet W,
      ∑ mn ∈ mertensPositivePhysicalPairCarrier (W / p),
        zeroTargetMellinPhysicalSuperLcmFourCorner W p (r p) mn.1 mn.2) =
      zeroTargetMellinCompletePostRootCo W r -
        zeroTargetMellinCompletePostRootDiv W r := by
  unfold zeroTargetMellinCompletePostRootCo
    zeroTargetMellinCompletePostRootDiv
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro p hp
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro mn hmn
  rcases mem_postRootPrimeFamilySet.mp hp with ⟨hpRoot, _hpW, hpPrime⟩
  rcases mem_mertensPositivePhysicalPairCarrier.mp hmn with
    ⟨ha1, haq, hb1, hbq, _hablt⟩
  have hqLt : W / p < p :=
    (Nat.div_lt_iff_lt_mul hpPrime.pos).2 ((Nat.sqrt_lt).1 hpRoot)
  have hpa : ¬ p ∣ mn.1 := by
    intro hdiv
    have hp_le : p ≤ mn.1 := Nat.le_of_dvd ha1 hdiv
    omega
  have hpb : ¬ p ∣ mn.2 := by
    intro hdiv
    have hp_le : p ≤ mn.2 := Nat.le_of_dvd hb1 hdiv
    omega
  exact zeroTargetMellinPhysicalSuperLcmFourCorner_eq_co_sub_div
    (hr0 p hp) hpPrime hpa hpb

/-- **Complete fresh-prime families have nonpositive normalized NNS covariance.**

This is the normalized form of the existing complete-cube nonpositivity theorem.
Positive target-zero covariance therefore cannot be generated in the complete
fresh-prime interior. -/
theorem zeroTargetMellinCompletePostRootNNSNormalized_nonpos
    (W : ℕ) (r : ℕ → ℝ)
    (hr0 : ∀ p ∈ postRootPrimeFamilySet W, 0 ≤ r p)
    (hr2 : ∀ p ∈ postRootPrimeFamilySet W, r p ≤ 2) :
    zeroTargetMellinCompletePostRootNNSNormalized W r ≤ 0 := by
  have hraw :=
    sum_all_zeroTargetMellinCompletePostRootFamilies_nonpos W r hr0 hr2
  have hsplit :=
    sum_all_zeroTargetMellinCompletePostRootFamilies_eq_co_sub_div W r hr0
  have hexcess :
      zeroTargetMellinCompletePostRootCo W r -
        zeroTargetMellinCompletePostRootDiv W r ≤ 0 := by
    rw [← hsplit]
    exact hraw
  unfold zeroTargetMellinCompletePostRootNNSNormalized
  rw [nnsZeroTargetNormalizedCovariance_nonpos_iff
    (zeroTargetMellinCompletePostRootCo_nonneg W r)
    (zeroTargetMellinCompletePostRootDiv_nonneg W r)]
  linarith

/-- Package the two compiled facts that define the remaining positive channel:
complete fresh-prime normalized covariance is nonpositive, while the genuinely
clipped outgoing energy is strictly contracted. -/
theorem nnsComplete_nonpos_and_clippedEnergy_contracts
    (W : ℕ) (r : ℕ → ℝ)
    (hr0 : ∀ p ∈ postRootPrimeFamilySet W, 0 ≤ r p)
    (hr2 : ∀ p ∈ postRootPrimeFamilySet W, r p ≤ 2) :
    zeroTargetMellinCompletePostRootNNSNormalized W r ≤ 0 ∧
      ∀ parent : ℕ × ℕ,
        postRootCovarianceCriticalClippedOutgoingEnergy W parent ≤
          (79 / 81 : ℝ) * postRootCovarianceReciprocalPairEnergy parent := by
  constructor
  · exact zeroTargetMellinCompletePostRootNNSNormalized_nonpos W r hr0 hr2
  · intro parent
    exact postRootCovarianceCriticalClippedOutgoingEnergy_le_79_over_81 W parent

end RHLean.Proof
