import Mathlib
import «research.VF_MID_SIGNED_SEAT_CHARGE»
import «research.VF_MID_RECURSIVE_CHILD_INJECTIVE»

/-!
# Well-founded descent of the recursive VF owner tree

The signed VF child-tree identity from #849 writes the block tracking defect on
terminal and recursive least-prime owner children.  PR #850 then proves two
facts about the recursive sector for `R >= 7`:

* every recursive stripped child `m` satisfies `2R < m < R^2`;
* distinct recursive owners have disjoint child carriers.

The upper inequality has a stronger consequence that is useful for coherence
arguments.  If a recursive child is re-indexed by its square scale

    S = floor(sqrt m),

then `S < R`.  Hence recursive owner transport is well founded in square
scale: no recursive lineage, and in fact no arbitrary sequence of recursive
scale choices, can persist forever.

This file kernel-checks that statement and packages the exact minimal-counter-
example principle needed by a future VF positive-coherence argument.

Important scope: this kills *lineage persistence*.  It does not by itself prove
that a supercritical aggregate endpoint-coherence excursion must select one of
these recursive children.  That aggregate-to-child forcing statement is the
remaining arithmetic seam.  No probabilistic independence, Li approximation,
PNT error estimate, or RH hypothesis is used here.
-/

noncomputable section

namespace RHLean.Analysis

attribute [local instance] Classical.propDecidable

/-- A one-step descent in square scale generated by a parity-late recursive
owner child.  The `7 <= R` guard is exactly the range in which #850 proves
cross-owner child injectivity and the sharp child geometry. -/
def VFMidRecursiveScaleStep (R S : ℕ) : Prop :=
  7 ≤ R ∧
    ∃ p m : ℕ,
      p ∈ vfMidSquareBandLateRecursiveOwners R ∧
      m ∈ vfMidSquareBandCompositeOwnerChildren R p ∧
      Nat.sqrt m = S

/-- Every recursive stripped child lives at a strictly smaller square scale. -/
theorem vfMidLateRecursiveOwner_child_sqrt_lt
    {R p m : ℕ} (hR : 7 ≤ R)
    (hp : p ∈ vfMidSquareBandLateRecursiveOwners R)
    (hm : m ∈ vfMidSquareBandCompositeOwnerChildren R p) :
    Nat.sqrt m < R := by
  apply (Nat.sqrt_lt').2
  exact vfMidLateRecursiveOwner_child_lt_square hR hp hm

/-- **Strict recursive scale descent.**  Every VF recursive-scale step decreases
the natural square index. -/
theorem vfMidRecursiveScaleStep_lt
    {R S : ℕ} (h : VFMidRecursiveScaleStep R S) :
    S < R := by
  rcases h with ⟨hR, p, m, hp, hm, rfl⟩
  exact vfMidLateRecursiveOwner_child_sqrt_lt hR hp hm

/-- Recursive scale transport cannot return to the same square scale. -/
theorem vfMidRecursiveScaleStep_irrefl (R : ℕ) :
    ¬ VFMidRecursiveScaleStep R R := by
  intro h
  exact (Nat.lt_irrefl R) (vfMidRecursiveScaleStep_lt h)

/-- A finite chain of recursive square-scale descents. -/
def VFMidRecursiveScaleChain (f : ℕ → ℕ) (n : ℕ) : Prop :=
  ∀ k < n, VFMidRecursiveScaleStep (f k) (f (k + 1))

/-- Every recursive step in a chain decreases by at least one, so after `n`
steps the current scale plus `n` is bounded by the starting scale. -/
theorem vfMidRecursiveScaleChain_add_le
    (f : ℕ → ℕ) :
    ∀ n : ℕ, VFMidRecursiveScaleChain f n →
      f n + n ≤ f 0 := by
  intro n
  induction n with
  | zero =>
      intro _h
      simp
  | succ n ih =>
      intro h
      have hprefix : VFMidRecursiveScaleChain f n := by
        intro k hk
        exact h k (by omega)
      have hprev : f n + n ≤ f 0 := ih hprefix
      have hstep :
          VFMidRecursiveScaleStep (f n) (f (n + 1)) :=
        h n (by omega)
      have hlt : f (n + 1) < f n :=
        vfMidRecursiveScaleStep_lt hstep
      omega

/-- **No indefinitely persistent recursive lineage.**  Starting at scale
`f 0`, a recursive chain cannot even have `f 0 + 1` steps. -/
theorem not_vfMidRecursiveScaleChain_beyond_start
    (f : ℕ → ℕ) :
    ¬ VFMidRecursiveScaleChain f (f 0 + 1) := by
  intro h
  have hbound :=
    vfMidRecursiveScaleChain_add_le f (f 0 + 1) h
  omega

/-- In particular there is no infinite sequence of recursive VF scale steps. -/
theorem not_vfMidRecursiveScaleChain_infinite
    (f : ℕ → ℕ) :
    ¬ (∀ k : ℕ, VFMidRecursiveScaleStep (f k) (f (k + 1))) := by
  intro h
  apply not_vfMidRecursiveScaleChain_beyond_start f
  intro k hk
  exact h k

/-- A property of square scales is recursively persistent when every occurrence
forces another occurrence on a recursive child scale. -/
def VFMidRecursiveScalePersistent (Q : ℕ → Prop) : Prop :=
  ∀ R : ℕ, Q R →
    ∃ S : ℕ, VFMidRecursiveScaleStep R S ∧ Q S

/-- **Minimal-counterexample principle for VF recursive persistence.**

No nonempty property can reproduce itself on a recursive child at every
occurrence, because the child square scale is strictly smaller.  This is the
exact well-founded logical mechanism used by the earlier covariance-descent
architecture, now kernel-checked on the native VF owner tree. -/
theorem vfMidRecursiveScalePersistent_impossible
    {Q : ℕ → Prop}
    (hdesc : VFMidRecursiveScalePersistent Q) :
    ∀ R : ℕ, ¬ Q R := by
  intro R
  induction R using Nat.strong_induction_on with
  | h R ih =>
      intro hQR
      obtain ⟨S, hstep, hQS⟩ := hdesc R hQR
      exact ih S (vfMidRecursiveScaleStep_lt hstep) hQS

/-- The #849 signed child-tree identity together with strict recursive scale
descent.  This packages the exact input available for an aggregate coherence
argument: the block defect is on the child tree, and every recursive child lies
below the current square scale. -/
theorem vfMidOddCompositeTrackingDefect_eq_signed_child_tree_with_strict_descent
    (R : ℕ) (hR : 7 ≤ R) :
    vfMidOddCompositeTrackingDefect R =
        (∑ p ∈ vfMidSquareBandLateTerminalOwners R,
          vfMidOddFractionalPrimeSeatWeight R *
            ((vfMidSquareBandCompositeOwnerChildren R p).card : ℝ)) +
        (∑ p ∈ vfMidSquareBandLateRecursiveOwners R,
          vfMidOddFractionalPrimeSeatWeight R *
            ((vfMidSquareBandOwnerRoughChildren R p).card : ℝ)) -
        (1 - vfMidOddFractionalPrimeSeatWeight R) *
          (vfMidIntegerBlockPrimeSupply R : ℝ) ∧
      ∀ p ∈ vfMidSquareBandLateRecursiveOwners R,
        ∀ m ∈ vfMidSquareBandCompositeOwnerChildren R p,
          Nat.sqrt m < R := by
  constructor
  · exact vfMidOddCompositeTrackingDefect_eq_signed_child_tree R (by omega)
  · intro p hp m hm
    exact vfMidLateRecursiveOwner_child_sqrt_lt hR hp hm

end RHLean.Analysis
