import Mathlib
import RHLean.Analysis.DynamicVioleBaseline
import RHLean.Analysis.NativePNTSquarePrefixTailGeometry

/-!
# Strong-induction geometry for adjacent Viole tail advancement

A fixed square annulus is the seed for an adjacent cutoff advance, but it cannot
by itself pay an `e(N) log N` improvement uniformly as `N` tends to infinity.
The correct propagation mechanism is strong induction on the first endpoint
that could violate the new slope.

At such an endpoint every proper reciprocal quotient already above the new
cutoff `L` is controlled by the new slope.  The only quotients that still use
the old slope lie in the finite transition strip `M <= q < L`; in the divisor
coordinate this is the moving reciprocal interval

`N / L < d <= N / M`.

This module freezes that geometry independently of any analytic majorant.  The
remaining Viole arithmetic may therefore be stated as a finite-history seed /
transition estimate rather than as a disguised uniform tail assertion.
-/

noncomputable section

namespace RHLean.Analysis

/-- A local strong-induction law for advancing a true PNT tail from cutoff `M`
to cutoff `L` with a smaller slope.  The step is allowed to use the new slope
at every strictly smaller endpoint already beyond `L`, together with the old
`M`-tail. -/
def NativePNTDirectCutoffInductionLaw
    (M L : Nat) (alpha alpha' : Real) : Prop :=
  2 <= M ∧ M <= L ∧ 0 < alpha' ∧ alpha' <= alpha ∧
    forall N : Nat, L <= N ->
      (forall q : Nat, L <= q -> q < N ->
        |nativePNTError q| <= alpha' * (q : Real)) ->
      (forall q : Nat, M <= q ->
        |nativePNTError q| <= alpha * (q : Real)) ->
      |nativePNTError N| <= alpha' * (N : Real)

/-- **Direct tail propagation by strong induction.**  Once the local step can
use already-contracted smaller quotients, no global `CubicGainFromTo` predicate
is needed. -/
theorem nativePNTDirectCutoffInductionLaw_step
    (M L : Nat) (alpha alpha' : Real)
    (htail : PrimeSieveStateDependentSelbergTailAbove M alpha)
    (hlaw : NativePNTDirectCutoffInductionLaw M L alpha alpha') :
    PrimeSieveStateDependentSelbergTailAbove L alpha' := by
  rcases hlaw with ⟨hM2, hML, halpha', _hale, hstep⟩
  rcases htail with ⟨_hM2, _halpha, htail⟩
  refine ⟨hM2.trans hML, halpha', ?_⟩
  have hall : forall N : Nat, L <= N ->
      |nativePNTError N| <= alpha' * (N : Real) := by
    intro N
    induction N using Nat.strong_induction_on with
    | h N ih =>
        intro hLN
        exact hstep N hLN
          (fun q hLq hqN => ih q hqN hLq) htail
  exact hall

/-- Divisors whose quotient is in the old-only transition strip
`M <= N/d < L`.  It is exactly the part of the `L` small-quotient region that
was not already below the old cutoff `M`. -/
def nativePNTDirectCutoffTransitionDivisorSet
    (N M L : Nat) : Finset Nat :=
  nativePNTSquarePrefixSmallQuotientFiberSet N L \
    nativePNTSquarePrefixSmallQuotientFiberSet N M

/-- The transition strip is the moving reciprocal annulus
`N/L < d <= N/M`. -/
theorem nativePNTDirectCutoffTransitionDivisorSet_eq_Icc
    (N M L : Nat) (hM : 1 <= M) (hL : 1 <= L) (hML : M <= L) :
    nativePNTDirectCutoffTransitionDivisorSet N M L =
      Finset.Icc (N / L + 1) (N / M) := by
  rw [nativePNTDirectCutoffTransitionDivisorSet,
    nativePNTSquarePrefixSmallQuotientFiberSet_eq_Icc N L hL,
    nativePNTSquarePrefixSmallQuotientFiberSet_eq_Icc N M hM]
  have hdiv : N / L <= N / M :=
    Nat.div_le_div_left hML (by omega)
  ext d
  simp only [Finset.mem_sdiff, Finset.mem_Icc]
  omega

/-- Equivalent quotient-space characterization of the moving transition
annulus. -/
theorem mem_nativePNTDirectCutoffTransitionDivisorSet_iff
    (N M L d : Nat) :
    d ∈ nativePNTDirectCutoffTransitionDivisorSet N M L ↔
      d ∈ Finset.Icc 1 N ∧ M <= N / d ∧ N / d < L := by
  unfold nativePNTDirectCutoffTransitionDivisorSet
    nativePNTSquarePrefixSmallQuotientFiberSet
  simp only [Finset.mem_sdiff, Finset.mem_filter, Finset.mem_Icc, not_lt]
  tauto

/-- At the first subdoubling endpoint the moving transition annulus is empty.
This is why the adjacent-square argument needs a finite-history seed before
strong-induction propagation can take over. -/
theorem nativePNTDirectCutoffTransitionDivisorSet_endpoint_eq_empty_of_subdoubling
    (M L : Nat) (hM : 1 <= M) (hML : M <= L) (hsub : L < 2 * M) :
    nativePNTDirectCutoffTransitionDivisorSet L M L = ∅ := by
  rw [nativePNTDirectCutoffTransitionDivisorSet_eq_Icc L M L hM
    (hM.trans hML) hML]
  have hLL : L / L = 1 := Nat.div_self (by omega)
  have hLM : L / M = 1 := by
    exact Nat.div_eq_of_lt_le (by simpa using hML) (by simpa using hsub)
  rw [hLL, hLM]
  simp

/-- Every reciprocal quotient generated by a nontrivial divisor is strictly
smaller than its endpoint, so the strong-induction hypothesis applies as soon
as that quotient has reached `L`. -/
theorem nativePNTDirectCutoff_recursive_quotient_lt
    (N d : Nat) (hN : 1 <= N) (hd : 2 <= d) :
    N / d < N := by
  exact Nat.div_lt_self (by omega) (by omega)

/-- At a Viole adjacent-square endpoint the old-only transition strip is empty
from `r >= 3` onward. -/
theorem violeClockDirectCutoffTransition_endpoint_eq_empty
    (r : Nat) (hr : 3 <= r) :
    nativePNTDirectCutoffTransitionDivisorSet
        (violeClockCutoff (r + 1))
        (violeClockCutoff r)
        (violeClockCutoff (r + 1)) = ∅ := by
  have hM : 1 <= violeClockCutoff r := by
    unfold violeClockCutoff
    nlinarith
  exact
    nativePNTDirectCutoffTransitionDivisorSet_endpoint_eq_empty_of_subdoubling
      (violeClockCutoff r) (violeClockCutoff (r + 1)) hM
      (violeClockCutoff_le_succ r)
      (violeClockCutoff_succ_lt_two_mul r hr)

end RHLean.Analysis
