import Mathlib
import RHLean.Proof.PostRootPartnerEulerMemory
import RHLean.Proof.CanonicalRoughTruncatedWheelManyPrimeTelescope
import RHLean.Proof.CanonicalRoughColumnAbelBridge
import RHLean.Analysis.SquareRootMatchedTransport
import RHLean.Proof.StableFarWallUnitRenewalCentering
import RHLean.Proof.PhysicalQ2ExceptionalTerminalSynthesis
import RHLean.Proof.PostRootPartnerMellinInterpolation
import RHLean.Proof.LogSquareCorrectionQ2Tower

/-!
# Exact Euler-hazard alignment of the post-root partner ledger

The post-root partner bridge gives two exact local facts before any norm:

* the reciprocal physical defect at prime `p` carries the native exchange rate
  `1 / p` against the corresponding signed boundary charge;
* already-processed larger primes transport every later defect by their Euler
  factors `1 - 1 / q`.

Consequently a boundary charge created at a later/smaller prime has coefficient

```text
(1 / p) * product_{q processed earlier} (1 - 1 / q).
```

This file isolates that coefficient algebra.  It is the finite statement behind
the logarithmic-coordinate heuristic: on a complete descending prime band the
Euler tail is expected, after classical Mertens/PNT comparison, to behave like a
ratio of logarithms, so the prime density and the reciprocal `1/p` convert the
transported mass into approximately uniform mass in `log p`.

Nothing asymptotic is used below.  In particular, no Mertens-product estimate,
PNT error estimate, or RH-scale cancellation is asserted.  The point is to make
the exact finite hazard measure explicit, and to connect it literally to the
already-compiled transported physical-defect ledger.  The separate physical to
canonical-column identification remains a carrier theorem, not an estimate.
-/

noncomputable section

open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

open RHLean.Analysis
open RHLean.Arithmetic
open CanonicalRoughPrimeAdditionDescent

attribute [local instance] Classical.propDecidable

/-! ## Scalar Euler-hazard mass -/

/-- Total reciprocal hazard mass generated by a chronological prime list.  The
head is the earlier/larger coordinate, so it transports the complete tail by
its Euler factor before its own native `1/p` atom is added. -/
def postRootEulerHazardMass : List ℕ → ℝ
  | [] => 0
  | p :: ps =>
      canonicalRoughEulerFactor p * postRootEulerHazardMass ps +
        1 / (p : ℝ)

@[simp] theorem postRootEulerHazardMass_nil :
    postRootEulerHazardMass [] = 0 := by
  rfl

@[simp] theorem postRootEulerHazardMass_cons (p : ℕ) (ps : List ℕ) :
    postRootEulerHazardMass (p :: ps) =
      canonicalRoughEulerFactor p * postRootEulerHazardMass ps +
        1 / (p : ℝ) := by
  rfl

/-- **Exact hazard normalization.**  The transported reciprocal atoms exhaust
exactly the complement of the finite Euler product:

`sum transported (1/p) = 1 - product (1 - 1/p)`.

This is pure finite algebra and does not require primality or an asymptotic
estimate. -/
theorem postRootEulerHazardMass_eq_one_sub_eulerProduct (ps : List ℕ) :
    postRootEulerHazardMass ps =
      1 - canonicalRoughPrimeListEulerProduct ps := by
  induction ps with
  | nil =>
      simp [postRootEulerHazardMass, canonicalRoughPrimeListEulerProduct]
  | cons p ps ih =>
      simp only [postRootEulerHazardMass_cons,
        canonicalRoughPrimeListEulerProduct_cons]
      rw [ih]
      unfold canonicalRoughEulerFactor
      ring

/-! ## Boundary-valued Euler-hazard ledger -/

/-- Euler-transported boundary ledger for an arbitrary signed boundary field.
The current boundary is inserted with its native reciprocal-prime coefficient;
all later/smaller boundaries are transported by the current Euler factor. -/
def postRootEulerHazardLedger (boundary : ℕ → ℂ) : List ℕ → ℂ
  | [] => 0
  | p :: ps =>
      (canonicalRoughEulerFactor p : ℂ) *
          postRootEulerHazardLedger boundary ps +
        boundary p / (p : ℂ)

@[simp] theorem postRootEulerHazardLedger_nil (boundary : ℕ → ℂ) :
    postRootEulerHazardLedger boundary [] = 0 := by
  rfl

@[simp] theorem postRootEulerHazardLedger_cons
    (boundary : ℕ → ℂ) (p : ℕ) (ps : List ℕ) :
    postRootEulerHazardLedger boundary (p :: ps) =
      (canonicalRoughEulerFactor p : ℂ) *
          postRootEulerHazardLedger boundary ps +
        boundary p / (p : ℂ) := by
  rfl

/-- A later block is transported by the complete Euler product of every earlier
coordinate.  This is the exact finite form of the tail-product coefficient. -/
theorem postRootEulerHazardLedger_append
    (boundary : ℕ → ℂ) (pre post : List ℕ) :
    postRootEulerHazardLedger boundary (pre ++ post) =
      (canonicalRoughPrimeListEulerProduct pre : ℂ) *
          postRootEulerHazardLedger boundary post +
        postRootEulerHazardLedger boundary pre := by
  induction pre with
  | nil =>
      simp [postRootEulerHazardLedger, canonicalRoughPrimeListEulerProduct]
  | cons p pre ih =>
      simp only [List.cons_append, postRootEulerHazardLedger_cons,
        canonicalRoughPrimeListEulerProduct_cons]
      rw [ih]
      push_cast
      ring

/-! ## Literal connection to the #540 physical defect ledger -/

/-- Reciprocal-normalized signed boundary charge of one physical Euler step.
By definition this is the current prime times the reciprocal physical defect.
For the post-root bridge this is the quantity whose division by `p` recovers the
native defect atom. -/
def squareRootCanonicalRoughPhysicalStepBoundaryCharge
    (R : ℕ) (step : CanonicalRoughPhysicalEulerStep) : ℂ :=
  (step.1 : ℂ) * squareRootCanonicalRoughPhysicalStepDefect R step

/-- Transport the signed boundary charges with their native `1/p` exchange rate
and the exact chronological Euler factors. -/
def squareRootCanonicalRoughTransportedBoundaryChargeLedger
    (R : ℕ) : List CanonicalRoughPhysicalEulerStep → ℂ
  | [] => 0
  | step :: steps =>
      (canonicalRoughEulerFactor step.1 : ℂ) *
          squareRootCanonicalRoughTransportedBoundaryChargeLedger R steps +
        squareRootCanonicalRoughPhysicalStepBoundaryCharge R step /
          (step.1 : ℂ)

/-- **The #540 transported physical-defect ledger is exactly the transported
boundary-charge hazard ledger.**  No norm is taken.  The only hypothesis needed
to undo the local scaling is that each chronological coordinate is a genuine
prime, hence nonzero. -/
theorem squareRootCanonicalRoughTransportedBoundaryChargeLedger_eq_defectLedger
    (R : ℕ) (steps : List CanonicalRoughPhysicalEulerStep)
    (hprime : ∀ step ∈ steps, step.1.Prime) :
    squareRootCanonicalRoughTransportedBoundaryChargeLedger R steps =
      squareRootCanonicalRoughTransportedDefectLedger R steps := by
  induction steps with
  | nil =>
      rfl
  | cons step steps ih =>
      have hp : step.1.Prime := hprime step (by simp)
      have htail : ∀ s ∈ steps, s.1.Prime := by
        intro s hs
        exact hprime s (by simp [hs])
      have hp0 : (step.1 : ℂ) ≠ 0 := by
        exact_mod_cast hp.ne_zero
      have hscale :
          squareRootCanonicalRoughPhysicalStepBoundaryCharge R step /
              (step.1 : ℂ) =
            squareRootCanonicalRoughPhysicalStepDefect R step := by
        unfold squareRootCanonicalRoughPhysicalStepBoundaryCharge
        field_simp [hp0]
      simp only [squareRootCanonicalRoughTransportedBoundaryChargeLedger,
        squareRootCanonicalRoughTransportedDefectLedger]
      rw [ih htail, hscale]

/-- The exact canonical comparison target already present in the repository:
the literal unweighted column over a full prime prefix lands on the signed Abel
primitive.  This theorem is restated here only to pin the endpoint of the new
hazard-coordinate splice next to the #685 chronology. -/
theorem postRootCanonicalColumn_logAlignmentTarget (X K : ℕ) :
    (∑ q ∈ primesUpTo K,
      (primorialTruncatedSignedReciprocalCube (primesUpTo (q - 1)) (X / q) -
        primorialSignedContractionFactor (primesUpTo (q - 1)))) =
      primorialTruncatedWheelAbelPrimitive X K := by
  exact canonicalUnweightedColumn_eq_abelPrimitive X K

/-! ## FAR-4 splice: exact q² carrier first, energy second -/

/-- The centered q²-descended carrier left after every nonunit strict crossing
is routed to its unique next child. Every occurrence multiplicity is retained. -/
def farFourQ2CenteredTower (R : ℕ) : ℂ :=
  ∑ y ∈ lowWheelFarPrimeQ2DescendedTriples R,
    (1 - (lowWheelFarPrimeQ2CrossingNextMultiplicity R y : ℂ)) *
      canonicalMoebiusWeight y.2.1

/-- The part of the old stable-far census not yet on the q²-descended carrier:
centered unit returns plus the already-owned terminal products. This term is
kept explicit; it must be eliminated or charged only after the newer post-root
partner chronology is used. -/
def farFourTerminalRemainder (R : ℕ) : ℂ :=
  (∑ p ∈ lowWheelFarPrimeUnitProducts R,
      ((lowWheelFarPrimeQ2UnitCrossingMultiplicity R p : ℂ) - 1)) +
    ∑ n ∈ lowWheelFrozenTopFarOwnedProducts R,
      canonicalMoebiusWeight n

/-- Terminal products split into their far-unit baseline and the disjoint old
owned products. -/
theorem lowWheelFarWallTerminalProducts_mass_eq_unit_add_owned (R : ℕ) :
    (∑ n ∈ lowWheelFarWallTerminalProducts R,
        canonicalMoebiusWeight n) =
      (∑ p ∈ lowWheelFarPrimeUnitProducts R,
        canonicalMoebiusWeight p) +
      ∑ n ∈ lowWheelFrozenTopFarOwnedProducts R,
        canonicalMoebiusWeight n := by
  unfold lowWheelFarWallTerminalProducts
  rw [Finset.sum_union (lowWheelFarPrimeUnitProducts_disjoint_owned R)]

/-- **Signed q² carrier normal form.** Before any norm, every nonunit renewal
has landed on the existing q²-descended carrier. The only leftover from the old
stable-far census is displayed explicitly as `farFourTerminalRemainder`; it is
not silently declared an error term. -/
theorem lowWheelFrozenTopFarResidual_eq_neg_q2CenteredTower_sub_terminal
    (R : ℕ) (hR : 56 ≤ R) :
    lowWheelFrozenTopFarResidual R =
      -farFourQ2CenteredTower R - farFourTerminalRemainder R := by
  have hfar :=
    lowWheelFrozenTopFarResidual_eq_neg_childFarSlices_sub_stableRenewal_sub_terminal
      R hR
  have hcenter :=
    lowWheelFarPrimeChildFar_add_crossingRenewal_add_unitTerminal_eq_centered R
  have hterminal := lowWheelFarWallTerminalProducts_mass_eq_unit_add_owned R
  unfold farFourQ2CenteredTower farFourTerminalRemainder
  rw [hterminal] at hfar
  rw [hfar]
  linear_combination -hcenter

/-- Literal factor-four FAR splice with the root-envelope constant exposed. -/
def FarFourSplice (C : ℝ) : Prop :=
  ∀ R : ℕ, ∀ K : ℝ,
    56 ≤ R →
    LowerMertensCriticalEnvelope R K →
    ‖lowWheelFrozenTopFarResidual R‖ ^ 2 ≤
      4 * ∑ q ∈ (primesUpTo (R - 1)).erase 2,
        rawQ2ChildEnergyReal R q +
      C * (R : ℝ) ^ 2 * K

/-- The named splice is exactly the body of the pre-existing FAR-4 terminal
criterion, not a new analytic hypothesis in another coordinate. -/
theorem frozenTopFarFourEnergy_iff_exists_nonneg_farFourSplice :
    FrozenTopFarFourEnergyStatement ↔
      ∃ C : ℝ, 0 ≤ C ∧ FarFourSplice C := by
  rfl

/-- Quantitative support interface after the exact signed reassembly. This is
where any genuinely remaining arithmetic estimate must live. -/
def FarFourQ2TowerEnergySupport (C : ℝ) : Prop :=
  ∀ R : ℕ, ∀ K : ℝ,
    56 ≤ R →
    LowerMertensCriticalEnvelope R K →
    ‖farFourQ2CenteredTower R‖ ^ 2 ≤
      2 * ∑ q ∈ (primesUpTo (R - 1)).erase 2,
        rawQ2ChildEnergyReal R q ∧
    ‖farFourTerminalRemainder R‖ ^ 2 ≤
      C * (R : ℝ) ^ 2 * K

private theorem norm_add_sq_le_two (u v : ℂ) :
    ‖u + v‖ ^ 2 ≤ 2 * ‖u‖ ^ 2 + 2 * ‖v‖ ^ 2 := by
  have hnorm := norm_add_le u v
  have hu : 0 ≤ ‖u‖ := norm_nonneg _
  have hv : 0 ≤ ‖v‖ := norm_nonneg _
  have huv : 0 ≤ ‖u + v‖ := norm_nonneg _
  nlinarith [sq_nonneg (‖u‖ - ‖v‖)]

/-- Once q² energy support and root-scale terminal support are supplied, the
literal FAR-4 inequality follows by one final two-vector synthesis. -/
theorem farFourQ2TowerEnergySupport_implies_splice
    {C : ℝ} (hsupport : FarFourQ2TowerEnergySupport C) :
    FarFourSplice (2 * C) := by
  intro R K hR hK
  rcases hsupport R K hR hK with ⟨hTower, hTerminal⟩
  have hdecomp :=
    lowWheelFrozenTopFarResidual_eq_neg_q2CenteredTower_sub_terminal R hR
  have hnorm := norm_add_sq_le_two
    (farFourQ2CenteredTower R) (farFourTerminalRemainder R)
  have hnorm' :
      ‖lowWheelFrozenTopFarResidual R‖ ^ 2 ≤
        2 * ‖farFourQ2CenteredTower R‖ ^ 2 +
          2 * ‖farFourTerminalRemainder R‖ ^ 2 := by
    rw [hdecomp]
    have heq :
        -farFourQ2CenteredTower R - farFourTerminalRemainder R =
          -(farFourQ2CenteredTower R + farFourTerminalRemainder R) := by ring
    rw [heq, norm_neg]
    exact hnorm
  calc
    ‖lowWheelFrozenTopFarResidual R‖ ^ 2 ≤
        2 * ‖farFourQ2CenteredTower R‖ ^ 2 +
          2 * ‖farFourTerminalRemainder R‖ ^ 2 := hnorm'
    _ ≤ 2 *
          (2 * ∑ q ∈ (primesUpTo (R - 1)).erase 2,
            rawQ2ChildEnergyReal R q) +
        2 * (C * (R : ℝ) ^ 2 * K) := by
          gcongr
    _ = 4 * ∑ q ∈ (primesUpTo (R - 1)).erase 2,
          rawQ2ChildEnergyReal R q +
        (2 * C) * (R : ℝ) ^ 2 * K := by ring

/-- The support interface instantiates the pre-existing FAR-4 terminal theorem. -/
theorem farFourQ2TowerEnergySupport_implies_frozenTopFarFourEnergy
    {C : ℝ} (hC : 0 ≤ C)
    (hsupport : FarFourQ2TowerEnergySupport C) :
    FrozenTopFarFourEnergyStatement := by
  refine ⟨2 * C, by positivity, ?_⟩
  exact farFourQ2TowerEnergySupport_implies_splice hsupport

/-- The already-compiled terminal engine then closes RH. -/
theorem riemannHypothesis_of_farFourQ2TowerEnergySupport
    {C : ℝ} (hC : 0 ≤ C)
    (hsupport : FarFourQ2TowerEnergySupport C) :
    RiemannHypothesis := by
  exact riemannHypothesis_of_frozenTopFarFourEnergy
    (farFourQ2TowerEnergySupport_implies_frozenTopFarFourEnergy hC hsupport)

/-- Pin the exact arithmetic commutator next to the splice. -/
theorem farFour_logMatch : LOG_MATCH := log_match

end RHLean.Proof
