import Mathlib
import RHLean.Analysis.TwoWheelQ2Compensation
import RHLean.Proof.SquareRootLowPrimeGoRecursiveDescent

/-!
# Go / recovered q-square compatibility

The algebraic recovered packet really is q-square self-similar, but the literal
Go daughter at owner `q` is a different object: the frozen predecessor-prime
cube `F_{q^-}(X/q^2)`.  This module records the exact compatibility defect.

There are two regimes.

* If `X/q^2 < q`, the predecessor cube is already complete at the daughter
  cutoff and the Go daughter is ordinary Mertens exactly.
* If `q <= X/q^2`, the difference from ordinary Mertens is an explicit Mertens
  increment plus the already-compiled smaller-owner Go strips.  Nothing may be
  discarded or renamed as endpoint error.

This is finite exact bookkeeping; no estimate is introduced.
-/

open scoped ArithmeticFunction.Moebius BigOperators

noncomputable section

namespace RHLean.Proof

open RHLean.Arithmetic
open RHLean.Analysis

/-- Difference between the full recovered/Mertens q-square daughter and the
literal Go predecessor-cube daughter. -/
def q2GoRecoveredCompatibilityDefect (q X : ℕ) : ℤ :=
  mertensSummatoryInt (X / (q * q)) -
    squareRootLowPrimeGoWallSquareResidual q X

/-- **Completed daughter compatibility.**  Once the q-square cutoff is below
its owner, the two daughter notions agree identically. -/
theorem q2GoRecoveredCompatibilityDefect_eq_zero_of_complete
    {q X : ℕ} (hq : q.Prime) (hcomplete : X / (q * q) < q) :
    q2GoRecoveredCompatibilityDefect q X = 0 := by
  unfold q2GoRecoveredCompatibilityDefect
  rw [squareRootLowPrimeGoWallSquareResidual_eq_mertensSummatoryInt
    hq hcomplete]
  ring

/-- **Unfinished daughter compatibility formula.**  When the daughter cutoff
has not yet fallen below `q`, the exact obstruction to replacing the literal Go
daughter by full Mertens is a Mertens increment plus the smaller-owner frozen
strips.  This is the two-wheel boundary term which a LOCAL-BLOCK theorem must
carry or cancel. -/
theorem q2GoRecoveredCompatibilityDefect_eq_increment_add_smallerOwnerStrips
    {q X : ℕ} (hq : q.Prime) (hunfinished : q ≤ X / (q * q)) :
    q2GoRecoveredCompatibilityDefect q X =
      (mertensSummatoryInt (X / (q * q)) - mertensSummatoryInt (q - 1)) +
        ∑ r ∈ primesUpTo (q - 1),
          (frozenPrimeUniverseMass (primesUpTo (r - 1))
              ((X / (q * q)) / r) -
            frozenPrimeUniverseMass (primesUpTo (r - 1)) ((q - 1) / r)) := by
  unfold q2GoRecoveredCompatibilityDefect
  rw [squareRootLowPrimeGoWallSquareResidual_eq_mertensPred_sub_smallerOwnerStrips
    hq hunfinished]
  ring

/-- For owner 3 the predecessor cube is already a complete nonempty Boolean
cube as soon as the q-square daughter cutoff is at least 2, hence the literal
Go residual vanishes exactly. -/
theorem squareRootLowPrimeGoWallSquareResidual_three_eq_zero
    {X : ℕ} (hcut : 2 ≤ X / (3 * 3)) :
    squareRootLowPrimeGoWallSquareResidual 3 X = 0 := by
  rw [squareRootLowPrimeGoWallSquareResidual_eq_squareCutoff]
  apply frozenPrimeUniverseMass_eq_zero_of_complete_old_cube
  · refine ⟨2, ?_⟩
    exact mem_primesUpTo.mpr ⟨Nat.prime_two, by norm_num⟩
  · intro p hp
    exact prime_of_mem_primesUpTo hp
  · have hprod : primeFaceProduct (primesUpTo (3 - 1)) = 2 := by
      native_decide
    rw [hprod]
    exact hcut

/-- Therefore, in the long q=3 regime the entire compatibility defect is the
full lower-scale Mertens value.  In particular it is not an `O(1)` CRT endpoint
artifact generated by the local 3^2 coordinate. -/
theorem q2GoRecoveredCompatibilityDefect_three_eq_mertens
    {X : ℕ} (hcut : 2 ≤ X / (3 * 3)) :
    q2GoRecoveredCompatibilityDefect 3 X =
      mertensSummatoryInt (X / (3 * 3)) := by
  unfold q2GoRecoveredCompatibilityDefect
  rw [squareRootLowPrimeGoWallSquareResidual_three_eq_zero hcut]
  ring

/-- Concrete certificate at the first square stage where this distinction is
visible: at `X = 35 = 6^2-1`, the literal q=3 Go daughter is zero while the full
Mertens daughter at cutoff 3 is `-1`. -/
theorem q2GoRecoveredCompatibilityDefect_three_thirtyFive :
    q2GoRecoveredCompatibilityDefect 3 35 = -1 := by
  rw [q2GoRecoveredCompatibilityDefect_three_eq_mertens (by norm_num)]
  native_decide

end RHLean.Proof
